import type { ServicePageData } from "@/lib/services";

export const expandedServicePages = {
  "ux-ui-design": {
    slug: "ux-ui-design",
    code: "CREATE / UXUI",
    eyebrow: "LEADFLOWAI / UX + UI DESIGN",
    title: "UX/UI design dla stron i produktów webowych, które prowadzą użytkownika do decyzji.",
    lead: "Projektujemy architekturę informacji, ścieżki, makiety, interfejs, komponenty i stany responsywne jako system gotowy do realnego wdrożenia.",
    directAnswer: "UX/UI design w LeadFlowAI nie kończy się na makiecie ekranu. Łączymy cele biznesowe, potrzeby użytkownika, strukturę treści, konwersję, dostępność i ograniczenia technologiczne, aby projekt dało się wdrożyć bez zgadywania intencji autora.",
    capabilities: ["UX", "UI", "Architektura informacji", "Makiety", "Design system", "Responsive", "Dostępność", "CRO"],
    outcomes: [
      { title: "Mniej niejasności", description: "Struktura i stany interfejsu są rozstrzygnięte przed implementacją zamiast powstawać przypadkiem w kodzie." },
      { title: "Spójny produkt", description: "Komponenty i zasady projektowe skalują się na kolejne podstrony, moduły i urządzenia." },
      { title: "Projekt gotowy do mierzenia", description: "CTA i kluczowe ścieżki są powiązane z konkretnymi celami użytkownika i biznesu." },
    ],
    deliverables: [
      { index: "01", title: "Discovery + architektura informacji", description: "Cele, odbiorcy, priorytety treści, mapa informacji i krytyczne ścieżki użytkownika.", tags: ["Discovery", "IA", "User flow", "Content"] },
      { index: "02", title: "Makiety", description: "Układ ekranów i hierarchia informacji bez przedwczesnego przywiązywania się do dekoracji.", tags: ["Wireframe", "Mobile-first", "CRO", "States"] },
      { index: "03", title: "System wizualny", description: "Typografia, rytm, komponenty, stany, tokeny i zasady interakcji tworzące spójny język produktu.", tags: ["UI", "Tokens", "Components", "Design system"] },
      { index: "04", title: "Handoff + QA", description: "Specyfikacja zachowania, breakpointów, focus/hover/touch i review implementacji w przeglądarce.", tags: ["Handoff", "Responsive", "A11y", "QA"] },
    ],
    process: [
      { title: "Problem", description: "Ustalamy co użytkownik ma zrozumieć, znaleźć lub zrobić." },
      { title: "Struktura", description: "Projektujemy informację i przepływy przed warstwą wizualną." },
      { title: "System", description: "Budujemy komponenty i hierarchię interfejsu." },
      { title: "Prototyp", description: "Sprawdzamy kluczowe zachowania i stany." },
      { title: "Review wdrożenia", description: "Weryfikujemy zgodność projektu z działającą wersją." },
    ],
    faqs: [
      { question: "Czy można zamówić sam UX/UI bez developmentu?", answer: "Tak. Projekt może być samodzielnym etapem, pod warunkiem że zakres handoffu i odpowiedzialność za późniejszą implementację są jasno ustalone." },
      { question: "Czy projektujecie mobile osobno?", answer: "Projektujemy system responsywny. Nie traktujemy telefonu jako pomniejszonego desktopu — kolejność, gęstość i interakcje mogą wymagać innych decyzji." },
      { question: "Czy design system ma sens dla małej strony?", answer: "Tak, ale jego skala powinna odpowiadać projektowi. Nawet mały serwis korzysta na spójnych tokenach i komponentach, bez budowania korporacyjnego systemu na zapas." },
    ],
    related: ["strony-internetowe", "interaktywne-strony", "dostepnosc-wcag"],
  },
  "aplikacje-webowe": {
    slug: "aplikacje-webowe",
    code: "CREATE / WEB APP",
    eyebrow: "LEADFLOWAI / APLIKACJE WEBOWE",
    title: "Aplikacje webowe i panele, które przenoszą proces biznesowy do przeglądarki.",
    lead: "Budujemy dedykowane aplikacje, portale, dashboardy, panele klienta, narzędzia operacyjne i workflow, kiedy klasyczna strona nie wystarcza.",
    directAnswer: "Aplikacja webowa ma sens wtedy, gdy użytkownik nie tylko czyta treść, ale wykonuje pracę: zarządza danymi, składa zlecenie, konfiguruje produkt, śledzi proces lub współpracuje z systemem. Zakres zaczynamy od modelu danych, ról i krytycznych operacji, a nie od listy ekranów.",
    capabilities: ["Web app", "Dashboardy", "Autoryzacja", "Model danych", "API", "Workflow", "Role", "Observability"],
    outcomes: [
      { title: "Proces w jednym miejscu", description: "Dane, stany i działania są uporządkowane zamiast rozproszone między arkuszami, e-mailami i ręcznymi krokami." },
      { title: "Kontrola uprawnień", description: "Role i operacje są projektowane zgodnie z rzeczywistym sposobem pracy użytkowników." },
      { title: "Możliwość integracji", description: "Aplikacja może łączyć się z istniejącymi usługami i API zamiast tworzyć kolejny izolowany silos." },
    ],
    deliverables: [
      { index: "01", title: "Model domeny", description: "Encje, stany, role, uprawnienia i kluczowe operacje opisujące proces biznesowy.", tags: ["Domain", "Data", "Roles", "Permissions"] },
      { index: "02", title: "UX aplikacji", description: "Nawigacja, formularze, dashboardy, stany pustki, błędy i operacje zaprojektowane pod realną pracę.", tags: ["UX", "Forms", "Dashboard", "States"] },
      { index: "03", title: "Frontend + granica backendu", description: "Implementacja interfejsu i bezpiecznych granic API zgodnie z wymaganiami projektu.", tags: ["React", "TypeScript", "API", "Security"] },
      { index: "04", title: "QA + obserwowalność", description: "Walidacja krytycznych przepływów, błędów, uprawnień i podstaw monitorowania działania.", tags: ["QA", "Logs", "Monitoring", "Recovery"] },
    ],
    process: [
      { title: "Discovery procesu", description: "Rozpisujemy pracę użytkowników, dane i wyjątki." },
      { title: "Model", description: "Definiujemy domenę, role i granice systemu." },
      { title: "Prototyp", description: "Sprawdzamy najważniejszy workflow przed rozbudową." },
      { title: "Build", description: "Implementujemy kolejne moduły według priorytetu." },
      { title: "Operacyjny QA", description: "Testujemy błędy, uprawnienia, odzyskiwanie i działanie na docelowych urządzeniach." },
    ],
    faqs: [
      { question: "Czym aplikacja webowa różni się od strony?", answer: "Strona głównie publikuje i prowadzi do działania. Aplikacja utrzymuje stan i pozwala wykonywać złożone operacje na danych lub procesie." },
      { question: "Czy aplikacja musi mieć logowanie?", answer: "Nie. Autoryzacja jest potrzebna tylko wtedy, gdy dane lub operacje wymagają rozróżnienia użytkowników i uprawnień." },
      { question: "Czy można zacząć od MVP?", answer: "Tak. W wielu projektach najlepszym podejściem jest mały, produkcyjny workflow zamiast budowania całego systemu przed pierwszą weryfikacją." },
    ],
    related: ["web-development", "integracje-api", "pwa"],
  },
  "cms-headless": {
    slug: "cms-headless",
    code: "CREATE / CMS",
    eyebrow: "LEADFLOWAI / CMS + HEADLESS",
    title: "CMS i headless CMS dobrane do sposobu publikowania, a nie do przyzwyczajeń wykonawcy.",
    lead: "Projektujemy edycję treści, modele danych i workflow publikacji tak, aby zespół mógł zmieniać to, co naprawdę wymaga częstych aktualizacji.",
    directAnswer: "CMS powinien uprościć pracę redakcyjną, nie przenosić do panelu całej złożoności strony. Najpierw określamy kto publikuje, co zmienia, jak często i jakie walidacje są potrzebne. Dopiero wtedy wybieramy klasyczny, headless lub całkowicie statyczny model.",
    capabilities: ["CMS", "Headless", "Model treści", "UX redakcyjny", "Preview", "Role", "Walidacja", "Migracja"],
    outcomes: [
      { title: "Prostsza edycja", description: "Redaktor pracuje na polach i strukturach odpowiadających treści zamiast na przypadkowym edytorze strony." },
      { title: "Kontrolowana publikacja", description: "Modele danych i walidacja ograniczają rozjeżdżanie się layoutu oraz krytycznych informacji." },
      { title: "Technologia bez lock-inu na siłę", description: "Dobieramy poziom CMS do potrzeb zamiast instalować ciężki system w projekcie, który go nie potrzebuje." },
    ],
    deliverables: [
      { index: "01", title: "Model treści", description: "Typy treści, pola, relacje, walidacje i odpowiedzialność redakcyjna.", tags: ["Schema", "Content", "Relations", "Validation"] },
      { index: "02", title: "Workflow redakcyjny", description: "Panel, preview, wersjonowanie lub role w zakresie uzasadnionym procesem publikacji.", tags: ["Editor", "Preview", "Roles", "Workflow"] },
      { index: "03", title: "Integracja frontendu", description: "Bezpieczne pobieranie i renderowanie treści z zachowaniem wydajności oraz SEO.", tags: ["API", "SSG", "SEO", "Performance"] },
      { index: "04", title: "Migracja + QA", description: "Przeniesienie treści i kontrola braków, formatowania, adresów oraz indeksowalności.", tags: ["Migration", "URLs", "QA", "Search"] },
    ],
    process: [
      { title: "Audyt redakcyjny", description: "Sprawdzamy kto i jak naprawdę aktualizuje serwis." },
      { title: "Model", description: "Projektujemy typy treści i relacje." },
      { title: "Integracja", description: "Łączymy CMS z frontendem i preview." },
      { title: "Migracja", description: "Przenosimy istniejącą treść, jeśli jest częścią zakresu." },
      { title: "QA redaktora", description: "Testujemy proces oczami osoby publikującej, nie tylko developera." },
    ],
    faqs: [
      { question: "Czy każda strona potrzebuje CMS?", answer: "Nie. Jeżeli treść zmienia się rzadko, prostszy model może być szybszy, bezpieczniejszy i tańszy w utrzymaniu." },
      { question: "Co daje headless CMS?", answer: "Oddziela warstwę redakcyjną od frontendu. To pomaga przy wielu kanałach lub własnym frontendzie, ale dodaje też zależności, więc nie jest automatycznie lepszy." },
      { question: "Czy można przenieść treści ze starego CMS?", answer: "Tak, po zmapowaniu danych, URL-i i jakości istniejącej treści. Migracji nie traktujemy jako ślepego kopiowania wszystkiego." },
    ],
    related: ["strony-internetowe", "modernizacja-stron", "copywriting-content"],
  },
  pwa: {
    slug: "pwa",
    code: "CREATE / PWA",
    eyebrow: "LEADFLOWAI / PROGRESSIVE WEB APP",
    title: "PWA tam, gdzie doświadczenie webowe rzeczywiście korzysta z możliwości aplikacji.",
    lead: "Projektujemy instalowalne doświadczenia webowe, cache, tryby offline i funkcje urządzenia tylko wtedy, gdy wspierają konkretny proces użytkownika.",
    directAnswer: "Progressive Web App może połączyć dystrybucję strony internetowej z częścią zachowań aplikacji. Nie każda witryna potrzebuje instalacji lub offline. Najpierw ustalamy, które funkcje przynoszą wartość, a następnie projektujemy manifest, service worker, cache i fallback zgodnie z charakterem danych.",
    capabilities: ["PWA", "Service Worker", "Offline", "Instalacja", "Cache", "Web APIs", "Performance", "Fallback"],
    outcomes: [
      { title: "Szybki powrót", description: "Odpowiednia strategia cache może ograniczyć ponowne pobieranie zasobów i poprawić odczuwalną szybkość." },
      { title: "Kontrolowany offline", description: "Wybrane funkcje mogą działać bez sieci, jeśli model danych pozwala zrobić to bezpiecznie." },
      { title: "Jedna dystrybucja web", description: "Użytkownik korzysta z adresu WWW, a instalacja jest opcjonalną warstwą, nie osobnym sklepem aplikacji." },
    ],
    deliverables: [
      { index: "01", title: "Ocena sensu PWA", description: "Ocena, które funkcje instalacji, cache i offline mają realne uzasadnienie.", tags: ["Use case", "Offline", "Install", "Risk"] },
      { index: "02", title: "Manifest + instalacja", description: "Konfiguracja metadanych aplikacji i zachowania instalacji na wspieranych platformach.", tags: ["Manifest", "Icons", "Install", "Metadata"] },
      { index: "03", title: "Strategia service workera", description: "Jawna polityka cache, aktualizacji i fallbacku dla różnych typów zasobów.", tags: ["Cache", "SW", "Update", "Fallback"] },
      { index: "04", title: "Offline + QA", description: "Testy sieci, aktualizacji, błędów i zachowania na docelowych urządzeniach.", tags: ["Offline", "QA", "Mobile", "Recovery"] },
    ],
    process: [
      { title: "Use case", description: "Wybieramy funkcje, które mają działać bardziej aplikacyjnie." },
      { title: "Polityka danych", description: "Ustalamy co można cachować i jak aktualizować dane." },
      { title: "Implementacja", description: "Wdrażamy manifest, service worker i wybrane funkcje." },
      { title: "Tryby awarii", description: "Projektujemy zachowanie przy braku sieci i starej wersji cache." },
      { title: "QA urządzeń", description: "Testujemy instalację i działanie na rzeczywistych przeglądarkach." },
    ],
    faqs: [
      { question: "Czy PWA zastępuje aplikację natywną?", answer: "Czasem może, ale nie zawsze. Decydują wymagane API urządzenia, dystrybucja, praca w tle i ograniczenia platform." },
      { question: "Czy PWA działa offline?", answer: "Może działać częściowo lub szeroko offline, ale wymaga zaprojektowanej strategii danych. Nie należy automatycznie cachować wszystkiego." },
      { question: "Czy zwykła strona firmowa potrzebuje PWA?", answer: "Zwykle nie. PWA ma większy sens przy powracającym użyciu i funkcjach aplikacyjnych niż przy jednorazowym zapoznaniu się z ofertą." },
    ],
    related: ["aplikacje-webowe", "core-web-vitals", "web-development"],
  },
  "cro-optymalizacja-konwersji": {
    slug: "cro-optymalizacja-konwersji",
    code: "CONVERT / CRO",
    eyebrow: "LEADFLOWAI / CRO",
    title: "CRO: optymalizacja konwersji oparta na ścieżce, danych i realnych barierach użytkownika.",
    lead: "Analizujemy ofertę, hierarchię, CTA, formularze, dowody i zachowanie użytkowników, aby poprawiać konkretne punkty decyzji zamiast losowo zmieniać przyciski.",
    directAnswer: "Conversion Rate Optimization to proces identyfikowania miejsc, w których użytkownik nie rozumie oferty, nie ufa jej, nie znajduje następnego kroku albo napotyka tarcie techniczne. Zmiany powinny wynikać z hipotezy i danych, a nie z uniwersalnych trików sprzedażowych.",
    capabilities: ["CRO", "Lejki", "CTA", "Formularze", "Dowody", "Analityka", "Eksperymenty", "UX"],
    outcomes: [
      { title: "Mniej tarcia", description: "Usuwamy problemy utrudniające wykonanie właściwego działania na kluczowych etapach ścieżki." },
      { title: "Czytelniejsze decyzje", description: "Oferta, dowody i CTA są ustawione według pytań użytkownika, nie kolejności wygodnej dla autora strony." },
      { title: "Hipotezy do weryfikacji", description: "Zmiany mają opisany powód i sposób pomiaru, dzięki czemu można ocenić ich efekt." },
    ],
    deliverables: [
      { index: "01", title: "Mapa konwersji", description: "Główne wejścia, cele, mikro-konwersje i miejsca utraty użytkownika.", tags: ["Funnel", "Intent", "CTA", "Journey"] },
      { index: "02", title: "Audyt tarcia", description: "Analiza komunikatu, interfejsu, formularzy, błędów, mobile i elementów zaufania.", tags: ["UX", "Forms", "Mobile", "Trust"] },
      { index: "03", title: "Priorytety hipotez", description: "Lista zmian z opisanym problemem, spodziewanym wpływem, ryzykiem i metodą weryfikacji.", tags: ["Hypothesis", "Impact", "Risk", "Test"] },
      { index: "04", title: "Plan pomiaru", description: "Zdarzenia i raportowanie potrzebne do odróżnienia realnej zmiany od wrażenia.", tags: ["Analytics", "Events", "Baseline", "Review"] },
    ],
    process: [
      { title: "Cel", description: "Definiujemy konwersję i wartość biznesową." },
      { title: "Evidence", description: "Zbieramy dane ilościowe i obserwacje jakościowe." },
      { title: "Hipotezy", description: "Łączymy problemy z możliwymi rozwiązaniami." },
      { title: "Implementacja", description: "Wdrażamy zmiany według priorytetu." },
      { title: "Review", description: "Porównujemy zachowanie po zmianie z punktem odniesienia." },
    ],
    faqs: [
      { question: "Czy CRO oznacza A/B testy?", answer: "Nie zawsze. A/B test ma sens przy odpowiednim ruchu i pytaniu badawczym. Wcześniej często można usunąć oczywiste bariery UX lub pomiaru." },
      { question: "Czy można robić CRO bez analityki?", answer: "Można przeprowadzić audyt jakościowy, ale bez pomiaru trudniej ocenić wpływ zmian i ustalać kolejne priorytety." },
      { question: "Czy większa liczba CTA zwiększa konwersję?", answer: "Nie automatycznie. CTA powinny odpowiadać etapowi decyzji. Zbyt wiele równorzędnych akcji może zwiększyć chaos zamiast skuteczności." },
    ],
    related: ["analityka-webowa", "formularze-lead-generation", "landing-pages"],
  },
  "analityka-webowa": {
    slug: "analityka-webowa",
    code: "CONVERT / ANALYTICS",
    eyebrow: "LEADFLOWAI / ANALITYKA WWW",
    title: "Analityka webowa, która mierzy decyzje użytkownika, a nie tylko odsłony.",
    lead: "Projektujemy plan pomiaru, zdarzenia, konwersje i dashboardy wokół realnych pytań biznesowych z uwzględnieniem prywatności i jakości danych.",
    directAnswer: "Analityka strony powinna odpowiadać na konkretne pytania: skąd przychodzi użytkownik, czego szuka, gdzie odpada i które działania mają wartość. Najpierw projektujemy plan pomiaru, a dopiero potem dobieramy narzędzie i implementujemy zdarzenia.",
    capabilities: ["Plan pomiaru", "Zdarzenia", "Konwersje", "Lejki", "Dashboardy", "Atrybucja", "Prywatność", "QA"],
    outcomes: [
      { title: "Dane z kontekstem", description: "Zdarzenia opisują istotne działania, a nie generują tysiące sygnałów bez interpretacji." },
      { title: "Kontrola konwersji", description: "Kontakt, wysłanie formularza, zakup lub inne cele mają jawne definicje i walidację." },
      { title: "Podstawa optymalizacji", description: "SEO, CRO i rozwój produktu mogą korzystać z jednego modelu pomiarowego." },
    ],
    deliverables: [
      { index: "01", title: "Plan pomiaru", description: "Cele, KPI, mikro-konwersje, zdarzenia, parametry i pytania, które mają odpowiadać danym.", tags: ["KPI", "Events", "Goals", "Definitions"] },
      { index: "02", title: "Instrumentacja", description: "Implementacja zdarzeń i konwersji w warstwie strony lub managera tagów zależnie od architektury.", tags: ["Events", "Tags", "Data layer", "QA"] },
      { index: "03", title: "Granica prywatności", description: "Ocena zakresu danych, zgód i ograniczenia zbierania do tego, co ma uzasadnienie.", tags: ["Privacy", "Consent", "Minimization", "Policy"] },
      { index: "04", title: "Raportowanie", description: "Czytelny zestaw widoków lub dashboardów wspierający realne decyzje biznesowe.", tags: ["Dashboard", "Funnel", "Segments", "Review"] },
    ],
    process: [
      { title: "Pytania", description: "Zaczynamy od decyzji, które dane mają wspierać." },
      { title: "Taksonomia", description: "Definiujemy zdarzenia i parametry." },
      { title: "Implementacja", description: "Wdrażamy instrumentację i zgody, jeśli są wymagane." },
      { title: "Walidacja", description: "Sprawdzamy duplikaty, błędne zdarzenia i konwersje." },
      { title: "Raportowanie", description: "Budujemy widoki i rytm przeglądu danych." },
    ],
    faqs: [
      { question: "Czy Google Analytics jest obowiązkowe?", answer: "Nie. Narzędzie dobieramy do pytań biznesowych, wymagań prywatności i ekosystemu marketingowego." },
      { question: "Czy każde kliknięcie trzeba mierzyć?", answer: "Nie. Nadmiar zdarzeń utrudnia analizę. Mierzymy działania potrzebne do odpowiedzi na konkretne pytania." },
      { question: "Czy analityka wymaga bannera cookies?", answer: "To zależy od zastosowanej technologii, konfiguracji i podstaw prawnych. Warstwę zgód dobieramy do faktycznie uruchomionego pomiaru, a nie odwrotnie." },
    ],
    related: ["cro-optymalizacja-konwersji", "seo", "formularze-lead-generation"],
  },
  "formularze-lead-generation": {
    slug: "formularze-lead-generation",
    code: "CONVERT / LEADS",
    eyebrow: "LEADFLOWAI / LEAD GENERATION",
    title: "Formularze i lead generation zaprojektowane jako kontrolowany przepływ, nie skrzynka na przypadkowe wiadomości.",
    lead: "Projektujemy briefy, formularze wieloetapowe, kwalifikację zapytań, walidację, routing i integracje z systemami obsługi leadów.",
    directAnswer: "Formularz leadowy ma zebrać dokładnie tyle informacji, ile potrzebne jest do kolejnego kroku. Zbyt krótki może generować bezużyteczne zapytania, a zbyt długi odstraszać. Projektujemy pola, logikę, walidację, bezpieczeństwo i dalszy routing jako jeden proces.",
    capabilities: ["Formularze", "Kwalifikacja", "Walidacja", "Multi-step", "Antyspam", "Routing", "CRM", "Analityka"],
    outcomes: [
      { title: "Lepszy kontekst", description: "Zespół otrzymuje informacje potrzebne do odpowiedzi zamiast rozpoczynać każdą rozmowę od odtwarzania podstaw." },
      { title: "Mniej błędów", description: "Walidacja i jasne komunikaty ograniczają niepoprawne lub niekompletne zgłoszenia." },
      { title: "Kontrolowany follow-up", description: "Lead może zostać przekazany do właściwego systemu, osoby lub kolejki zgodnie z procesem." },
    ],
    deliverables: [
      { index: "01", title: "Schemat leada", description: "Pola, warianty, warunki i minimalny zestaw danych potrzebny do dalszej obsługi.", tags: ["Fields", "Logic", "Qualification", "Data"] },
      { index: "02", title: "UX formularza", description: "Kolejność, grupowanie, komunikaty błędów, stany i wersja mobilna.", tags: ["UX", "Mobile", "Errors", "A11y"] },
      { index: "03", title: "Walidacja + bezpieczeństwo", description: "Walidacja po stronie interfejsu i serwera, limity oraz ochrona przed nadużyciem odpowiednia do architektury.", tags: ["Validation", "Spam", "Rate limit", "Security"] },
      { index: "04", title: "Routing + pomiar", description: "Przekazanie danych do uzgodnionego kanału i zdarzenia potrzebne do oceny konwersji.", tags: ["CRM", "Email", "API", "Analytics"] },
    ],
    process: [
      { title: "Cel formularza", description: "Ustalamy co ma wydarzyć się po wysłaniu." },
      { title: "Zakres danych", description: "Usuwamy pola bez uzasadnienia i definiujemy warunki." },
      { title: "Build", description: "Implementujemy interfejs, walidację i stany błędów." },
      { title: "Integracja", description: "Łączymy formularz z docelowym przepływem." },
      { title: "QA", description: "Testujemy błędy, spam, mobile i potwierdzenie odbioru." },
    ],
    faqs: [
      { question: "Czy dłuższy formularz zawsze konwertuje gorzej?", answer: "Nie. Jeżeli dodatkowe pytania są zrozumiałe i potrzebne do dalszego kroku, mogą poprawić jakość zapytań. Problemem jest nieuzasadnione tarcie." },
      { question: "Czy formularz można połączyć z CRM?", answer: "Tak, jeśli CRM udostępnia odpowiednią integrację lub API i zakres danych jest zgodny z procesem oraz wymaganiami prywatności." },
      { question: "Czy potrzebny jest CAPTCHA?", answer: "Nie zawsze. Mechanizm ochrony przed spamem dobieramy do realnego ryzyka, wolumenu i kosztu fałszywych zgłoszeń." },
    ],
    related: ["cro-optymalizacja-konwersji", "integracje-api", "analityka-webowa"],
  },
  "integracje-api": {
    slug: "integracje-api",
    code: "CONNECT / API",
    eyebrow: "LEADFLOWAI / INTEGRACJE API",
    title: "Integracje API, które łączą stronę z systemami biznesowymi w kontrolowany sposób.",
    lead: "Łączymy serwisy WWW z CRM, kalendarzami, płatnościami, systemami danych, narzędziami operacyjnymi i innymi API z obsługą błędów, autoryzacją i monitoringiem.",
    directAnswer: "Integracja API nie jest tylko wysłaniem jednego requestu. Trzeba ustalić źródło prawdy, autoryzację, format danych, retry, limity, timeout, idempotencję, błędy i zachowanie wtedy, gdy drugi system nie odpowiada. Dopiero wtedy połączenie nadaje się do produkcji.",
    capabilities: ["REST", "GraphQL", "Webhooks", "Auth", "Retry", "Idempotency", "Queues", "Monitoring"],
    outcomes: [
      { title: "Mniej ręcznej pracy", description: "Dane mogą przepływać między systemami bez przepisywania ich przez człowieka." },
      { title: "Jawne tryby awarii", description: "Integracja ma zdefiniowane zachowanie przy timeout, błędzie dostawcy i niepoprawnych danych." },
      { title: "Kontrola dostępu", description: "Sekrety i uprawnienia pozostają po stronie serwerowej zgodnie z rolą integracji." },
    ],
    deliverables: [
      { index: "01", title: "Kontrakt integracji", description: "Endpointy, format danych, kierunek synchronizacji, source of truth i warunki biznesowe.", tags: ["API", "Data", "Contract", "Ownership"] },
      { index: "02", title: "Auth + secrets", description: "Bezpieczne przechowywanie i użycie kluczy, tokenów lub OAuth zgodnie z wymaganiami dostawcy.", tags: ["OAuth", "Secrets", "Server", "Permissions"] },
      { index: "03", title: "Failure handling", description: "Timeout, retry, idempotencja, limity i komunikaty błędów dopasowane do procesu.", tags: ["Retry", "Timeout", "Idempotency", "Limits"] },
      { index: "04", title: "Monitoring + QA", description: "Logowanie kluczowych stanów i testy poprawnych oraz błędnych scenariuszy.", tags: ["Logs", "Monitoring", "QA", "Recovery"] },
    ],
    process: [
      { title: "Kontrakt", description: "Ustalamy co, kiedy i w którym kierunku ma przepływać." },
      { title: "Security boundary", description: "Definiujemy autoryzację i miejsce wykonywania operacji." },
      { title: "Prototype", description: "Sprawdzamy krytyczny przepływ na małym zakresie." },
      { title: "Resilience", description: "Dodajemy obsługę błędów i powtórzeń." },
      { title: "Production QA", description: "Testujemy zbliżone do realnych scenariusze i monitoring." },
    ],
    faqs: [
      { question: "Czy można połączyć dowolne dwa systemy?", answer: "Tylko jeśli istnieje techniczna możliwość wymiany danych: API, webhook, plik lub inny wspierany interfejs. Zakres zależy też od uprawnień i limitów dostawców." },
      { question: "Czy klucz API może być w kodzie przeglądarki?", answer: "Sekretnego klucza nie należy wystawiać klientowi. Operacje wymagające sekretu powinny przechodzić przez kontrolowaną warstwę serwerową." },
      { question: "Co jeśli zewnętrzne API przestanie działać?", answer: "Projektujemy zachowanie awaryjne zależnie od procesu: retry, kolejkę, zapis stanu, komunikat dla użytkownika lub ręczny fallback." },
    ],
    related: ["automatyzacje-www", "aplikacje-webowe", "formularze-lead-generation"],
  },
  "automatyzacje-www": {
    slug: "automatyzacje-www",
    code: "CONNECT / AUTOMATION",
    eyebrow: "LEADFLOWAI / AUTOMATYZACJE WWW",
    title: "Automatyzacje wokół strony: od leada i formularza po CRM, kalendarz i dalszy workflow.",
    lead: "Projektujemy przepływy danych i zdarzeń wokół strony tak, aby powtarzalne kroki były wykonywane automatycznie, ale nadal miały kontrolę błędów i możliwość audytu.",
    directAnswer: "Automatyzacja WWW ma sens wtedy, gdy usuwa powtarzalny krok bez ukrywania odpowiedzialności. Łączymy trigger ze strony z kolejnymi systemami, walidujemy dane, definiujemy warunki, logujemy wynik i projektujemy fallback, gdy któryś element łańcucha zawiedzie.",
    capabilities: ["Workflow", "Webhooks", "CRM", "Email", "Kalendarze", "No-code", "API", "Monitoring"],
    outcomes: [
      { title: "Szybsza obsługa", description: "Powtarzalne przekazywanie danych może dziać się od razu po zdarzeniu użytkownika." },
      { title: "Mniej przepisywania", description: "Te same dane nie muszą być ręcznie kopiowane między formularzem, skrzynką i systemem." },
      { title: "Jawny proces", description: "Automatyzacja ma opisane warunki, błędy i właściciela procesu zamiast działać jako niewidoczna magia." },
    ],
    deliverables: [
      { index: "01", title: "Mapa procesu", description: "Trigger, dane wejściowe, warunki, systemy docelowe i oczekiwany rezultat.", tags: ["Workflow", "Trigger", "Data", "Rules"] },
      { index: "02", title: "Automatyzacja", description: "Implementacja połączeń w technologii dobranej do procesu i wymagań utrzymania.", tags: ["Webhook", "API", "No-code", "Server"] },
      { index: "03", title: "Walidacja + błędy", description: "Kontrola danych, duplikatów, timeoutów i scenariuszy częściowego niepowodzenia.", tags: ["Validation", "Retry", "Errors", "Idempotency"] },
      { index: "04", title: "Monitoring + dokumentacja", description: "Informacja jak sprawdzić stan procesu, gdzie szukać błędu i jak ręcznie przejąć pracę.", tags: ["Logs", "Monitoring", "Runbook", "Recovery"] },
    ],
    process: [
      { title: "Obecny proces", description: "Rozpisujemy krok po kroku jak praca wygląda dziś." },
      { title: "Granice automatyzacji", description: "Wybieramy kroki, które można bezpiecznie zautomatyzować." },
      { title: "Build", description: "Łączymy trigger, dane i systemy." },
      { title: "Failure test", description: "Symulujemy duplikaty i niedostępność integracji." },
      { title: "Uruchomienie", description: "Dokumentujemy fallback i obserwujemy pierwsze rzeczywiste przebiegi." },
    ],
    faqs: [
      { question: "Czy automatyzacja wymaga Make lub n8n?", answer: "Nie. To tylko przykładowe narzędzia. Możemy użyć workflow platformy, kodu serwerowego lub połączenia obu podejść zależnie od krytyczności procesu." },
      { question: "Czy można automatycznie odpowiadać na każdy lead?", answer: "Technicznie często tak, ale treść i moment odpowiedzi powinny być kontrolowane. Automatyzacja nie powinna udawać ręcznej decyzji, której nie było." },
      { question: "Co z błędami automatyzacji?", answer: "Każdy istotny workflow powinien mieć możliwość wykrycia błędu i ręcznego przejęcia procesu." },
    ],
    related: ["integracje-api", "formularze-lead-generation", "integracje-ai"],
  },
  "integracje-ai": {
    slug: "integracje-ai",
    code: "INTELLIGENCE / AI",
    eyebrow: "LEADFLOWAI / INTEGRACJE AI",
    title: "Integracje AI dla stron i aplikacji, w których model ma jasno określoną rolę i granice.",
    lead: "Łączymy modele AI z interfejsem, bazą wiedzy i systemami biznesowymi tam, gdzie generowanie, klasyfikacja, wyszukiwanie lub ekstrakcja realnie usprawniają proces.",
    directAnswer: "Integracja AI powinna zaczynać się od zadania i kryterium jakości, nie od wyboru modelu. Definiujemy dane wejściowe, źródła, dozwolone działania, fallback, koszty, prywatność i sposób oceny odpowiedzi. Model jest komponentem systemu, nie źródłem nieograniczonego zaufania.",
    capabilities: ["LLM", "RAG", "Klasyfikacja", "Ekstrakcja", "Embeddings", "Tool use", "Guardrails", "Evaluation"],
    outcomes: [
      { title: "AI do konkretnej pracy", description: "Model odpowiada za określone zadanie zamiast być dodany tylko dlatego, że funkcja brzmi nowocześnie." },
      { title: "Kontrolowane źródła", description: "RAG lub inne źródła wiedzy są rozdzielone od treści generowanej i mają jasno określoną odpowiedzialność." },
      { title: "Fallback i ewaluacja", description: "System wie kiedy odmówić, poprosić o dane lub przekazać sprawę człowiekowi." },
    ],
    deliverables: [
      { index: "01", title: "Definicja zadania", description: "Wejście, wyjście, kryteria jakości, zakazane zachowania i przypadki brzegowe.", tags: ["Use case", "Quality", "Limits", "Safety"] },
      { index: "02", title: "Warstwa danych", description: "Źródła wiedzy, retrieval, transformacje lub kontekst potrzebny do wykonania zadania.", tags: ["RAG", "Embeddings", "Sources", "Context"] },
      { index: "03", title: "Integracja modelu", description: "Serwerowa komunikacja z providerem, limity, timeout, koszt i obsługa odpowiedzi.", tags: ["API", "Server", "Rate limit", "Cost"] },
      { index: "04", title: "Ewaluacja + monitoring", description: "Testy przykładowych i trudnych przypadków oraz obserwacja jakości po uruchomieniu.", tags: ["Evals", "Logs", "Fallback", "Monitoring"] },
    ],
    process: [
      { title: "Use case", description: "Ustalamy czy AI rzeczywiście jest dobrym narzędziem do problemu." },
      { title: "Dataset testowy", description: "Budujemy reprezentatywne przykłady wejść i oczekiwanych wyników." },
      { title: "Prototype", description: "Porównujemy modele i architekturę na ograniczonym zakresie." },
      { title: "Guardrails", description: "Dodajemy granice, fallback i kontrolę integracji." },
      { title: "Production observation", description: "Monitorujemy jakość, koszt i błędy bez zakładania, że model pozostanie niezmienny." },
    ],
    faqs: [
      { question: "Czy AI może mieć dostęp do CRM lub innych narzędzi?", answer: "Może, ale każde narzędzie powinno mieć minimalne wymagane uprawnienia, jawny zakres i walidację przed wykonaniem skutków ubocznych." },
      { question: "Czy RAG eliminuje halucynacje?", answer: "Nie. Może poprawić dostęp do właściwego kontekstu, ale model nadal może źle zinterpretować źródło lub wygenerować niepoprawny wniosek." },
      { question: "Czy trzeba korzystać z jednego dostawcy AI?", answer: "Nie. Architektura może być projektowana tak, aby provider był wymiennym elementem, jeśli wymagania biznesowe uzasadniają taką elastyczność." },
    ],
    related: ["chatboty-ai", "automatyzacje-www", "integracje-api"],
  },
  "core-web-vitals": {
    slug: "core-web-vitals",
    code: "CARE / PERFORMANCE",
    eyebrow: "LEADFLOWAI / CORE WEB VITALS",
    title: "Core Web Vitals i performance: optymalizacja rzeczywistego kosztu strony, nie tylko wyniku jednego testu.",
    lead: "Analizujemy LCP, INP, CLS, JavaScript, CSS, obrazy, fonty, rendering i third-party scripts, a poprawki priorytetyzujemy według realnego wpływu na użytkownika.",
    directAnswer: "Performance strony to połączenie czasu pobierania, kosztu parsowania i wykonania, renderowania oraz stabilności interfejsu. Core Web Vitals są ważnymi wskaźnikami, ale optymalizacja powinna usuwać źródła kosztu, a nie tylko manipulować pojedynczym laboratoryjnym wynikiem.",
    capabilities: ["LCP", "INP", "CLS", "JavaScript", "CSS", "Images", "Rendering", "Budgets"],
    outcomes: [
      { title: "Szybszy start", description: "Krytyczne zasoby i największy element treści są dostarczane bez zbędnych opóźnień." },
      { title: "Mniej blokowania", description: "Ograniczamy koszt JavaScript i długie zadania wpływające na responsywność interfejsu." },
      { title: "Stabilniejszy layout", description: "Rezerwacja przestrzeni i kontrola zasobów zmniejszają nieoczekiwane przesunięcia treści." },
    ],
    deliverables: [
      { index: "01", title: "Profil kosztu", description: "Analiza bundle, obrazów, fontów, third-party i krytycznej ścieżki renderowania.", tags: ["Bundle", "Images", "Fonts", "Network"] },
      { index: "02", title: "CWV diagnosis", description: "Identyfikacja elementów odpowiadających za LCP, INP i CLS w kontekście strony.", tags: ["LCP", "INP", "CLS", "RUM"] },
      { index: "03", title: "Optymalizacja runtime", description: "Lazy loading, code splitting, ograniczenie pracy renderera i ciężkich eventów zgodnie z potrzebą.", tags: ["JS", "Rendering", "Lazy", "Events"] },
      { index: "04", title: "Budżety regresji", description: "Progi lub kontrakty blokujące niekontrolowany wzrost krytycznych zasobów w kolejnych wdrożeniach.", tags: ["Budgets", "CI", "Regression", "QA"] },
    ],
    process: [
      { title: "Baseline", description: "Mierzymy stan przed zmianą i rozdzielamy dane lab od field data, jeśli są dostępne." },
      { title: "Profiling", description: "Szukamy źródła kosztu zamiast optymalizować objaw." },
      { title: "Fix", description: "Wdrażamy zmiany od największego wpływu." },
      { title: "Regression", description: "Porównujemy wynik i funkcjonalność po zmianie." },
      { title: "Budget", description: "Zabezpieczamy krytyczne parametry przed przypadkowym pogorszeniem." },
    ],
    faqs: [
      { question: "Czy wynik 100 w Lighthouse jest celem samym w sobie?", answer: "Nie. Lighthouse jest użytecznym narzędziem diagnostycznym, ale celem jest szybka i stabilna strona dla realnych użytkowników." },
      { question: "Czy animacje zawsze psują performance?", answer: "Nie. Problemem jest koszt implementacji. Transform i opacity są zwykle tańsze niż ciągłe operacje layoutowe, a ciężkie efekty wymagają ograniczeń i fallbacku." },
      { question: "Czy Core Web Vitals wpływają na SEO?", answer: "Są częścią szerszej oceny jakości doświadczenia, ale nie zastępują treści, intencji ani pozostałych fundamentów technicznego SEO." },
    ],
    related: ["audyt-strony", "strony-internetowe", "pwa"],
  },
  "dostepnosc-wcag": {
    slug: "dostepnosc-wcag",
    code: "CARE / WCAG",
    eyebrow: "LEADFLOWAI / DOSTĘPNOŚĆ WWW",
    title: "Dostępność WCAG projektowana w interfejsie i kodzie, a nie dopisywana jako nakładka.",
    lead: "Audytujemy i poprawiamy semantykę, klawiaturę, focus, kontrast, formularze, treść, motion i komponenty pod wymagania dostępności odpowiednie do projektu.",
    directAnswer: "Dostępność strony oznacza, że kluczowa treść i funkcje pozostają użyteczne dla osób korzystających z różnych sposobów nawigacji i technologii wspomagających. Pracujemy na realnym HTML, interakcji i treści; nie traktujemy nakładki accessibility jako zamiennika poprawnej implementacji.",
    capabilities: ["WCAG", "Keyboard", "Focus", "Semantic HTML", "Forms", "Contrast", "Reduced motion", "Testing"],
    outcomes: [
      { title: "Pełniejsza obsługa", description: "Kluczowe funkcje można wykonać bez polegania wyłącznie na myszy, kolorze lub animacji." },
      { title: "Lepsza semantyka", description: "Nagłówki, landmarki, etykiety i stany interfejsu są opisane w strukturze dokumentu." },
      { title: "Mniej regresji", description: "Zasady dostępności mogą wejść do komponentów i checklisty QA zamiast być jednorazową poprawką." },
    ],
    deliverables: [
      { index: "01", title: "Audyt dostępności", description: "Lista problemów z odniesieniem do kryteriów, wpływu na użytkownika i priorytetu.", tags: ["WCAG", "Audit", "Impact", "Priority"] },
      { index: "02", title: "Naprawy semantyczne", description: "Struktura HTML, etykiety, role i relacje poprawione u źródła.", tags: ["HTML", "ARIA", "Labels", "Landmarks"] },
      { index: "03", title: "Interakcja i formularze", description: "Focus, klawiatura, błędy, komunikaty i stany dynamiczne dostępne bez konkretnego urządzenia wejścia.", tags: ["Keyboard", "Focus", "Forms", "Errors"] },
      { index: "04", title: "Re-audyt", description: "Ponowna walidacja napraw i regresji w kluczowych ścieżkach.", tags: ["Regression", "QA", "Screen reader", "Review"] },
    ],
    process: [
      { title: "Zakres", description: "Ustalamy poziom, krytyczne ścieżki i wymagania prawne projektu." },
      { title: "Audit", description: "Łączymy testy automatyczne z ręczną oceną interakcji." },
      { title: "Remediation", description: "Naprawiamy przyczyny w komponentach i treści." },
      { title: "Re-test", description: "Sprawdzamy efekt zmian i regresje." },
      { title: "Maintenance", description: "Przenosimy najważniejsze zasady do dalszego procesu developmentu." },
    ],
    faqs: [
      { question: "Czy automatyczny skaner wystarczy do audytu WCAG?", answer: "Nie. Automaty wykrywają część problemów. Klawiatura, sens etykiet, kolejność focusu czy zrozumiałość komunikatów wymagają oceny ręcznej." },
      { question: "Czy można zrobić stronę całkowicie zgodną z WCAG bez zmian treści?", answer: "Nie zawsze. Część kryteriów dotyczy informacji i sposobu jej prezentacji, więc czasem konieczna jest także korekta treści lub materiałów." },
      { question: "Czy nakładka accessibility rozwiązuje problem?", answer: "Nie traktujemy nakładki jako zamiennika semantycznego kodu i poprawnej interakcji. Dostępność powinna wynikać z produktu." },
    ],
    related: ["ux-ui-design", "audyt-strony", "strony-internetowe"],
  },
  "bezpieczenstwo-stron": {
    slug: "bezpieczenstwo-stron",
    code: "CARE / SECURITY",
    eyebrow: "LEADFLOWAI / BEZPIECZEŃSTWO WWW",
    title: "Bezpieczeństwo stron i aplikacji webowych jako część architektury, nie ostatni plugin przed publikacją.",
    lead: "Projektujemy granice zaufania, sekrety, formularze, integracje, nagłówki i proces aktualizacji zgodnie z rzeczywistą powierzchnią ataku serwisu.",
    directAnswer: "Bezpieczeństwo strony zależy od architektury. Statyczna witryna ma inne ryzyka niż aplikacja z logowaniem i integracjami. Oceniamy gdzie są sekrety, dane użytkowników, operacje zapisu, zewnętrzne skrypty i uprawnienia, a zabezpieczenia dobieramy do tych granic.",
    capabilities: ["Headers", "Secrets", "Validation", "Auth", "Rate limits", "Dependencies", "CSP", "Recovery"],
    outcomes: [
      { title: "Mniejsza powierzchnia ataku", description: "Usuwamy zbędne endpointy, sekrety z klienta i uprawnienia, które nie są potrzebne do działania." },
      { title: "Kontrola wejścia", description: "Dane użytkownika i integracji są walidowane na odpowiednich granicach systemu." },
      { title: "Gotowość na błąd", description: "Backup, monitoring i plan odzyskiwania są częścią bezpieczeństwa operacyjnego." },
    ],
    deliverables: [
      { index: "01", title: "Mapa powierzchni ataku", description: "Publiczne endpointy, dane, sekrety, integracje i operacje o skutkach ubocznych.", tags: ["Threat model", "Data", "Endpoints", "Secrets"] },
      { index: "02", title: "Hardening", description: "Nagłówki, walidacja, limity, uprawnienia i konfiguracja odpowiednia do hostingu i aplikacji.", tags: ["CSP", "Headers", "Validation", "Limits"] },
      { index: "03", title: "Dependency + secret review", description: "Kontrola zależności i sposobu przechowywania kluczy oraz konfiguracji środowiska.", tags: ["Dependencies", "Secrets", "Env", "Updates"] },
      { index: "04", title: "Recovery boundary", description: "Backup, rollback i minimalny runbook dla awarii lub błędnego wdrożenia.", tags: ["Backup", "Rollback", "Runbook", "Monitoring"] },
    ],
    process: [
      { title: "Architecture review", description: "Ustalamy co jest publiczne, co prywatne i gdzie przepływają dane." },
      { title: "Threats", description: "Priorytetyzujemy realistyczne scenariusze zamiast checklisty bez kontekstu." },
      { title: "Hardening", description: "Wdrażamy zabezpieczenia w kodzie i infrastrukturze." },
      { title: "Adversarial QA", description: "Testujemy błędne wejścia, brak uprawnień i scenariusze nadużycia." },
      { title: "Maintenance", description: "Ustalamy aktualizacje, monitoring i odzyskiwanie." },
    ],
    faqs: [
      { question: "Czy HTTPS wystarczy do bezpieczeństwa strony?", answer: "Nie. HTTPS chroni transport, ale nie rozwiązuje problemów walidacji, uprawnień, sekretów, zależności ani błędnej logiki aplikacji." },
      { question: "Czy strona statyczna jest bezpieczniejsza?", answer: "Zwykle ma mniejszą powierzchnię ataku po stronie serwera, ale nadal może korzystać z zewnętrznych skryptów, formularzy i integracji, które wymagają kontroli." },
      { question: "Czy można zagwarantować brak włamania?", answer: "Nie. Bezpieczeństwo polega na redukcji ryzyka, warstwach ochrony, aktualizacjach i zdolności reagowania, nie na uczciwej gwarancji absolutnej." },
    ],
    related: ["hosting-deploy", "opieka-utrzymanie-stron", "audyt-strony"],
  },
  "hosting-deploy": {
    slug: "hosting-deploy",
    code: "CARE / DEPLOY",
    eyebrow: "LEADFLOWAI / HOSTING + DEPLOY",
    title: "Hosting i deployment dobrane do architektury strony, ruchu i poziomu odpowiedzialności.",
    lead: "Konfigurujemy publikację, domenę, DNS, HTTPS, środowiska, automatyczny build i rollback tak, aby wdrożenie było powtarzalne zamiast zależeć od ręcznego kopiowania plików.",
    directAnswer: "Hosting jest częścią systemu wdrożeniowego. Statyczny serwis, aplikacja server-rendered i backend z danymi mają inne wymagania. Dobieramy platformę, DNS, certyfikat, build, sekrety, cache i sposób rollbacku do realnego modelu aplikacji.",
    capabilities: ["DNS", "HTTPS", "CI/CD", "Static hosting", "SSR", "Cache", "Environments", "Rollback"],
    outcomes: [
      { title: "Powtarzalne wdrożenia", description: "Publikacja wynika z procesu build/deploy zamiast ręcznej operacji trudnej do odtworzenia." },
      { title: "Jasna konfiguracja domeny", description: "DNS, www/apex i HTTPS mają jednoznaczną konfigurację oraz źródło prawdy." },
      { title: "Szybszy rollback", description: "W razie błędu wiadomo jaki artefakt był wdrożony i jak wrócić do poprzedniego stanu." },
    ],
    deliverables: [
      { index: "01", title: "Hosting architecture", description: "Wybór modelu hostingu, środowisk i granic odpowiedzialności zgodnie z aplikacją.", tags: ["Hosting", "Static", "SSR", "Backend"] },
      { index: "02", title: "DNS + HTTPS", description: "Konfiguracja domeny, certyfikatu i kanonicznych hostów.", tags: ["DNS", "TLS", "CNAME", "Redirect"] },
      { index: "03", title: "CI/CD", description: "Automatyczny build, walidacja artefaktu i deployment z kontrolą branchy lub środowisk.", tags: ["CI", "Build", "Deploy", "Artifact"] },
      { index: "04", title: "Recovery", description: "Rollback, kopie konfiguracji i procedura podstawowej awarii wdrożeniowej.", tags: ["Rollback", "Backup", "Runbook", "Recovery"] },
    ],
    process: [
      { title: "Wymagania", description: "Ustalamy runtime, ruch, dane, dostępność i budżet operacyjny." },
      { title: "Platforma", description: "Dobieramy hosting bez nadmiarowej infrastruktury." },
      { title: "Pipeline", description: "Automatyzujemy build i deployment." },
      { title: "Domain cutover", description: "Przełączamy DNS i HTTPS z kontrolą propagacji." },
      { title: "Post-deploy QA", description: "Sprawdzamy routing, certyfikat, cache i krytyczne funkcje." },
    ],
    faqs: [
      { question: "Czy musicie być dostawcą hostingu?", answer: "Nie. Możemy wdrożyć serwis na platformie należącej do klienta i przekazać udokumentowaną konfigurację." },
      { question: "Czy każda strona potrzebuje serwera?", answer: "Nie. Wiele serwisów może być statycznie generowanych i publikowanych bez klasycznego serwera aplikacyjnego." },
      { question: "Czy można wdrażać automatycznie z GitHub?", answer: "Tak. CI/CD może budować i publikować stronę po zatwierdzonym merge, o ile platforma i model bezpieczeństwa na to pozwalają." },
    ],
    related: ["bezpieczenstwo-stron", "opieka-utrzymanie-stron", "web-development"],
  },
  "opieka-utrzymanie-stron": {
    slug: "opieka-utrzymanie-stron",
    code: "CARE / MAINTENANCE",
    eyebrow: "LEADFLOWAI / OPIEKA NAD STRONĄ",
    title: "Opieka i utrzymanie strony po publikacji: aktualizacje, monitoring, naprawy i rozwój bez utraty kontroli.",
    lead: "Utrzymujemy strony i aplikacje w modelu dopasowanym do technologii: aktualizacje, monitoring, backup, regresja, poprawki i małe etapy rozwoju.",
    directAnswer: "Strona po publikacji nadal zmienia się razem z przeglądarkami, zależnościami, ofertą i integracjami. Opieka powinna obejmować konkretne obowiązki: co monitorujemy, co aktualizujemy, jak reagujemy na błąd, co jest objęte SLA lub czasem reakcji, a co stanowi osobny etap rozwojowy.",
    capabilities: ["Maintenance", "Monitoring", "Updates", "Backup", "Regression", "Bugfix", "Content", "Roadmap"],
    outcomes: [
      { title: "Mniej niespodzianek", description: "Zmiany zależności, integracji i środowiska są obserwowane zanim staną się wielomiesięcznym długiem." },
      { title: "Szybsza reakcja", description: "Istnieje znany kanał zgłoszenia i kontekst techniczny potrzebny do diagnozy." },
      { title: "Rozwój etapami", description: "Małe poprawki i nowe funkcje mogą być planowane bez każdorazowego odtwarzania architektury projektu." },
    ],
    deliverables: [
      { index: "01", title: "Maintenance scope", description: "Jawna lista technologii, odpowiedzialności, aktualizacji i elementów nieobjętych opieką.", tags: ["Scope", "Ownership", "Updates", "SLA"] },
      { index: "02", title: "Monitoring", description: "Kontrola dostępności lub kluczowych błędów odpowiednia do typu systemu.", tags: ["Uptime", "Errors", "Logs", "Alerts"] },
      { index: "03", title: "Backup + recovery", description: "Kopia treści, danych lub konfiguracji tam, gdzie system ich wymaga, wraz z procedurą odtworzenia.", tags: ["Backup", "Restore", "Rollback", "Runbook"] },
      { index: "04", title: "Rozwój", description: "Backlog usprawnień i małe release'y walidowane przed produkcją.", tags: ["Backlog", "Release", "QA", "Roadmap"] },
    ],
    process: [
      { title: "Handover", description: "Dokumentujemy stan, dostęp, zależności i odpowiedzialności." },
      { title: "Baseline", description: "Sprawdzamy działanie kluczowych ścieżek i obecny dług techniczny." },
      { title: "Routine", description: "Ustalamy rytm aktualizacji, monitoringu i kopii." },
      { title: "Changes", description: "Każdą zmianę przeprowadzamy z walidacją odpowiednią do ryzyka." },
      { title: "Review", description: "Okresowo porządkujemy backlog i priorytety rozwoju." },
    ],
    faqs: [
      { question: "Czy utrzymujecie tylko strony zbudowane przez LeadFlowAI?", answer: "Możemy przejąć istniejący serwis po audycie technicznym i ustaleniu, za które elementy możemy realnie odpowiadać." },
      { question: "Czy opieka obejmuje nowe funkcje?", answer: "Małe zmiany mogą mieścić się w ustalonym modelu, a większe funkcje są osobnym etapem z zakresem i QA." },
      { question: "Czy backup wystarczy bez testu odtworzenia?", answer: "Nie daje pełnej pewności. Dla istotnych systemów warto okresowo sprawdzać, czy kopię można rzeczywiście wykorzystać do odtworzenia." },
    ],
    related: ["hosting-deploy", "bezpieczenstwo-stron", "core-web-vitals"],
  },
  "copywriting-content": {
    slug: "copywriting-content",
    code: "DISCOVER / CONTENT",
    eyebrow: "LEADFLOWAI / CONTENT + COPY",
    title: "Treść i copywriting dla stron: od architektury informacji po odpowiedzi, które wspierają decyzję i widoczność.",
    lead: "Projektujemy strukturę komunikatu, strony usługowe, sekcje answer-first, FAQ i treści wiedzy tak, aby użytkownik oraz system wyszukiwania rozumieli tę samą ofertę.",
    directAnswer: "Treść strony nie jest wypełniaczem między komponentami. Musi odpowiadać na intencję, wyjaśniać ofertę, pokazywać ograniczenia i prowadzić do kolejnego kroku. Łączymy copy sprzedażowe z architekturą SEO/AEO/GEO bez sztucznego upychania fraz.",
    capabilities: ["Copywriting", "Content architecture", "Service pages", "Answer-first", "FAQ", "SEO", "AEO", "GEO"],
    outcomes: [
      { title: "Jasna oferta", description: "Użytkownik szybciej rozumie co firma robi, dla kogo i jaki jest następny krok." },
      { title: "Treść pod intencję", description: "Każda ważna podstrona ma własny temat i rolę zamiast powielać te same ogólne akapity." },
      { title: "Lepsza cytowalność", description: "Definicje, warunki i odpowiedzi są wystarczająco konkretne, aby można je było przytoczyć bez utraty kontekstu." },
    ],
    deliverables: [
      { index: "01", title: "Mapa treści", description: "Tematy, intencje, typy podstron, pytania i relacje wewnętrzne między informacjami.", tags: ["Intent", "Topics", "IA", "Links"] },
      { index: "02", title: "Treść usługowa", description: "Direct answers, zakres, rezultaty, proces i FAQ napisane dla realnej decyzji użytkownika.", tags: ["Services", "Answers", "CRO", "FAQ"] },
      { index: "03", title: "Treść wiedzy", description: "Artykuły i klastry rozwijające kompetencje bez tworzenia masowych, cienkich stron pod frazy.", tags: ["Knowledge", "Clusters", "SEO", "AEO"] },
      { index: "04", title: "Public truth review", description: "Kontrola, czy treść nie zawiera wymyślonych rezultatów, klientów, certyfikatów lub obietnic bez dowodu.", tags: ["Claims", "Evidence", "Truth", "Review"] },
    ],
    process: [
      { title: "Intent", description: "Ustalamy co użytkownik chce wiedzieć i jaką decyzję podejmuje." },
      { title: "Architecture", description: "Dzielimy informacje na właściwe strony i sekcje." },
      { title: "Draft", description: "Piszemy answer-first, a potem rozwijamy kontekst i dowody." },
      { title: "Search review", description: "Sprawdzamy semantykę, linkowanie i relacje z innymi stronami." },
      { title: "Truth review", description: "Usuwamy twierdzenia, których nie można publicznie potwierdzić." },
    ],
    faqs: [
      { question: "Czy treść pod SEO musi być długa?", answer: "Nie. Powinna być kompletna względem intencji. Długość jest skutkiem potrzebnej informacji, a nie celem samym w sobie." },
      { question: "Czy piszecie treść tylko do nowych stron?", answer: "Nie. Możemy przebudować istniejącą architekturę treści i zachować wartościowe informacje podczas modernizacji." },
      { question: "Czy AEO oznacza same FAQ?", answer: "Nie. Najważniejsze odpowiedzi powinny istnieć również w głównej treści. FAQ jest tylko jednym z formatów." },
    ],
    related: ["seo-aeo-geo", "strony-internetowe", "cms-headless"],
  },
  "strony-wielojezyczne": {
    slug: "strony-wielojezyczne",
    code: "CREATE / I18N",
    eyebrow: "LEADFLOWAI / STRONY WIELOJĘZYCZNE",
    title: "Strony wielojęzyczne z poprawną architekturą języków, treści i widoczności.",
    lead: "Projektujemy routing językowy, hreflang, metadata, nawigację i workflow tłumaczeń tak, aby wersje językowe nie były przypadkowymi kopiami serwisu.",
    directAnswer: "Serwis wielojęzyczny wymaga decyzji o strukturze URL, języku domyślnym, relacjach hreflang, tłumaczeniu metadata, treści i elementów interfejsu. Automatyczne tłumaczenie może być częścią procesu, ale publiczna wersja powinna mieć kontrolę jakości odpowiednią do znaczenia treści.",
    capabilities: ["i18n", "Routing", "hreflang", "Locale", "Metadata", "CMS", "Translation", "SEO"],
    outcomes: [
      { title: "Jasne wersje językowe", description: "Każdy język ma jednoznaczny adres i relację z odpowiadającymi mu stronami." },
      { title: "Spójna nawigacja", description: "Zmiana języka prowadzi do odpowiednika aktualnej treści, jeśli taki istnieje." },
      { title: "Kontrola search", description: "Canonicale, hreflang i sitemap są zgodne z rzeczywistą architekturą lokalizacji." },
    ],
    deliverables: [
      { index: "01", title: "Architektura locale", description: "Języki, URL-e, fallbacki i reguły dostępności treści.", tags: ["Locale", "URLs", "Fallback", "Routing"] },
      { index: "02", title: "Search signals", description: "hreflang, canonical, metadata i sitemap zgodne z publicznymi wersjami językowymi.", tags: ["hreflang", "Canonical", "Metadata", "Sitemap"] },
      { index: "03", title: "Workflow tłumaczeń", description: "Proces tworzenia, review i aktualizacji treści zależnie od częstotliwości zmian.", tags: ["Translation", "Review", "CMS", "Workflow"] },
      { index: "04", title: "QA językowy", description: "Kontrola linków, przełącznika, brakujących tłumaczeń i zachowania formularzy.", tags: ["QA", "Navigation", "Forms", "Content"] },
    ],
    process: [
      { title: "Rynki i języki", description: "Ustalamy rzeczywiście potrzebne warianty." },
      { title: "Routing", description: "Projektujemy URL i relacje między lokalizacjami." },
      { title: "Content flow", description: "Ustalamy źródło treści i sposób tłumaczenia." },
      { title: "Implementation", description: "Wdrażamy locale, metadata i nawigację." },
      { title: "Search QA", description: "Sprawdzamy hreflang, canonical i sitemap." },
    ],
    faqs: [
      { question: "Czy każda wersja językowa musi mieć identyczną treść?", answer: "Nie. Oferta może różnić się rynkiem, ale różnice powinny być świadome, a nie wynikać z brakujących tłumaczeń." },
      { question: "Czy automatyczne tłumaczenie wystarczy?", answer: "Może przyspieszać pracę, ale treści sprzedażowe, prawne i specjalistyczne wymagają kontroli jakości odpowiedniej do ryzyka." },
      { question: "Czy język powinien być w subdomenie czy katalogu?", answer: "Oba modele są możliwe. Wybór zależy od domeny, zespołu, SEO i infrastruktury; ważniejsza jest spójność całego systemu." },
    ],
    related: ["strony-internetowe", "seo", "cms-headless"],
  },
} as const satisfies Record<string, ServicePageData>;

export type ExpandedServiceSlug = keyof typeof expandedServicePages;

export function getExpandedServicePage(slug: ExpandedServiceSlug): ServicePageData {
  return expandedServicePages[slug];
}

export const expandedServiceLinks = [
  { slug: "ux-ui-design", label: "UX/UI design", pillar: "CREATE" },
  { slug: "aplikacje-webowe", label: "Aplikacje webowe", pillar: "CREATE" },
  { slug: "cms-headless", label: "CMS / headless", pillar: "CREATE" },
  { slug: "pwa", label: "PWA", pillar: "CREATE" },
  { slug: "strony-wielojezyczne", label: "Strony wielojęzyczne", pillar: "CREATE" },
  { slug: "copywriting-content", label: "Treść i copywriting", pillar: "DISCOVER" },
  { slug: "cro-optymalizacja-konwersji", label: "CRO", pillar: "CONVERT" },
  { slug: "analityka-webowa", label: "Analityka webowa", pillar: "CONVERT" },
  { slug: "formularze-lead-generation", label: "Formularze i leady", pillar: "CONVERT" },
  { slug: "integracje-ai", label: "Integracje AI", pillar: "INTELLIGENCE" },
  { slug: "integracje-api", label: "Integracje API", pillar: "CONNECT" },
  { slug: "automatyzacje-www", label: "Automatyzacje WWW", pillar: "CONNECT" },
  { slug: "core-web-vitals", label: "Core Web Vitals", pillar: "CARE" },
  { slug: "dostepnosc-wcag", label: "Dostępność WCAG", pillar: "CARE" },
  { slug: "bezpieczenstwo-stron", label: "Bezpieczeństwo WWW", pillar: "CARE" },
  { slug: "hosting-deploy", label: "Hosting i deploy", pillar: "CARE" },
  { slug: "opieka-utrzymanie-stron", label: "Opieka i utrzymanie", pillar: "CARE" },
] as const;
