import type { Metadata } from "next";
import type { ServicePageData } from "@/lib/services";
import { site } from "@/lib/site";

export type ServicePillar = "CREATE" | "CONVERT" | "INTELLIGENCE" | "CONNECT" | "CARE";

export type ExtendedServicePage = ServicePageData & {
  key: string;
  label: string;
  pillar: ServicePillar;
  summary: string;
};

export const extendedServicePages = {
  "ux-ui-design": {
    key: "ux-ui-design",
    slug: "uslugi/ux-ui-design",
    label: "UX/UI Design",
    pillar: "CREATE",
    code: "CREATE / UX·UI",
    eyebrow: "LEADFLOWAI / UX + UI DESIGN",
    title: "UX/UI design oparty na zadaniu użytkownika, nie na dekoracji.",
    lead: "Projektujemy architekturę interfejsu, przepływy, komponenty i stany tak, aby produkt był czytelny, dostępny i gotowy do wdrożenia.",
    summary: "Od mapy zadań i wireframe do spójnego systemu komponentów i stanów interakcji.",
    directAnswer: "UX/UI design w LeadFlowAI obejmuje analizę zadania użytkownika, architekturę informacji, przepływy, wireframe, interfejs, komponenty, stany i przekazanie do developmentu. Projekt ma usuwać niejasności i wspierać konkretne działania, a nie tylko tworzyć atrakcyjny ekran.",
    capabilities: ["UX research", "User flows", "Wireframes", "UI", "Design system", "Prototype", "Accessibility", "Handoff"],
    outcomes: [
      { title: "Czytelne ścieżki", description: "Najważniejsze zadania użytkownika mają jasno zdefiniowany początek, kolejne decyzje i zakończenie." },
      { title: "Spójny interfejs", description: "Komponenty, stany i hierarchia są projektowane jako system zamiast zbioru niezależnych ekranów." },
      { title: "Mniej ryzyka we wdrożeniu", description: "Development dostaje decyzje dotyczące zachowania, responsywności i stanów, nie tylko statyczne makiety." },
    ],
    deliverables: [
      { index: "01", title: "UX map", description: "Cele, zadania, scenariusze, przepływy i priorytety informacji.", tags: ["Tasks", "Flows", "IA", "CRO"] },
      { index: "02", title: "Wireframes", description: "Układ treści i funkcji bez maskowania problemów warstwą wizualną.", tags: ["Wireframe", "Mobile", "States", "Content"] },
      { index: "03", title: "UI system", description: "Typografia, komponenty, spacing, stany i zachowanie responsive.", tags: ["UI", "Components", "Tokens", "Responsive"] },
      { index: "04", title: "Prototype + handoff", description: "Prototyp krytycznych interakcji i specyfikacja potrzebna do implementacji.", tags: ["Prototype", "Handoff", "A11y", "QA"] },
    ],
    process: [
      { title: "Problem", description: "Definiujemy użytkowników, cele i ograniczenia produktu." },
      { title: "Flow", description: "Układamy kolejność informacji i decyzji." },
      { title: "Interface", description: "Projektujemy komponenty i system wizualny." },
      { title: "Validation", description: "Sprawdzamy stany, mobile, klawiaturę i zgodność z zakresem." },
    ],
    faqs: [
      { question: "Czy UX/UI może być osobnym etapem bez developmentu?", answer: "Tak. Projekt może zakończyć się dokumentacją i prototypem gotowym do wdrożenia przez inny zespół." },
      { question: "Czy projekt obejmuje mobile?", answer: "Tak. Responsive nie jest dodatkiem; krytyczne układy i interakcje projektujemy od początku dla różnych szerokości i sposobów sterowania." },
      { question: "Czy robicie redesign istniejącego interfejsu?", answer: "Tak, jeżeli przed zmianą można zidentyfikować problemy obecnej architektury, zachowania i treści." },
    ],
    related: ["strony-internetowe", "uslugi/architektura-informacji", "uslugi/wcag-dostepnosc"],
  },
  "aplikacje-webowe": {
    key: "aplikacje-webowe",
    slug: "uslugi/aplikacje-webowe",
    label: "Aplikacje webowe",
    pillar: "CREATE",
    code: "CREATE / WEB APP",
    eyebrow: "LEADFLOWAI / APLIKACJE WEBOWE",
    title: "Aplikacje webowe i panele dopasowane do realnego procesu.",
    lead: "Budujemy aplikacje przeglądarkowe, panele, portale i narzędzia wewnętrzne z własną logiką, rolami, danymi i integracjami.",
    summary: "Dedykowana logika biznesowa, interfejs, dane, role i integracje w jednym produkcie webowym.",
    directAnswer: "Aplikacja webowa ma sens wtedy, gdy użytkownik nie tylko czyta treść, ale wykonuje proces: zarządza danymi, realizuje zadania, pracuje na rolach, generuje dokumenty albo komunikuje się z innymi systemami. Zakres projektujemy od modelu domeny i uprawnień po interfejs, API, testy i deployment.",
    capabilities: ["Product architecture", "Auth", "Roles", "Data", "API", "Dashboards", "Workflows", "QA"],
    outcomes: [
      { title: "Proces w jednym miejscu", description: "Dane i działania wynikają z jednego modelu zamiast ręcznego przenoszenia informacji między narzędziami." },
      { title: "Kontrola uprawnień", description: "Role i zakres dostępu są projektowane jawnie zgodnie z rzeczywistą odpowiedzialnością użytkowników." },
      { title: "Możliwość rozwoju", description: "Modułowa architektura pozwala dodawać kolejne funkcje bez przepisywania całej aplikacji." },
    ],
    deliverables: [
      { index: "01", title: "Domain + workflow model", description: "Encje, role, statusy, zdarzenia i krytyczne przepływy biznesowe.", tags: ["Domain", "Roles", "Workflow", "States"] },
      { index: "02", title: "Product UX", description: "Nawigacja, formularze, listy, dashboardy i obsługa błędów.", tags: ["UX", "Forms", "Dashboard", "A11y"] },
      { index: "03", title: "Application build", description: "Frontend, warstwa serwerowa, dane i integracje dobrane do wymagań.", tags: ["React", "TypeScript", "API", "Data"] },
      { index: "04", title: "Security + QA", description: "Walidacja, uprawnienia, testy krytycznych ścieżek i przygotowanie wdrożenia.", tags: ["Security", "Validation", "Tests", "Deploy"] },
    ],
    process: [
      { title: "Discovery", description: "Rozpisujemy proces, role i dane zamiast zaczynać od ekranów." },
      { title: "Architecture", description: "Definiujemy model domeny, interfejsy i granice systemu." },
      { title: "Build", description: "Implementujemy kolejne pionowe fragmenty produktu." },
      { title: "Acceptance", description: "Testujemy scenariusze użytkowników, błędy i uprawnienia." },
    ],
    faqs: [
      { question: "Czy aplikacja webowa może działać jako narzędzie wewnętrzne?", answer: "Tak. Nie każdy system musi być publiczny; panele operacyjne i narzędzia dla zespołu są typowym przypadkiem." },
      { question: "Czy aplikacja może integrować się z istniejącym API?", answer: "Tak, jeśli zakres i możliwości API są znane. Integrację projektujemy razem z obsługą błędów i uprawnień." },
      { question: "Czy potrzebna jest od razu pełna wersja produktu?", answer: "Nie. Często lepiej zacząć od zamkniętego MVP obejmującego najważniejszy proces i dopiero potem rozwijać kolejne moduły." },
    ],
    related: ["web-development", "uslugi/integracje-api", "uslugi/integracje-crm"],
  },
  "cms-headless": {
    key: "cms-headless",
    slug: "uslugi/cms-headless",
    label: "CMS i headless CMS",
    pillar: "CREATE",
    code: "CREATE / CMS",
    eyebrow: "LEADFLOWAI / CMS + HEADLESS",
    title: "CMS dobrany do procesu publikacji, a nie odwrotnie.",
    lead: "Projektujemy klasyczne i headless CMS-y tak, aby zespół mógł bezpiecznie zarządzać treścią bez rozbijania struktury strony.",
    summary: "Model treści, role redakcyjne, workflow publikacji i frontend rozdzielone tam, gdzie daje to realną wartość.",
    directAnswer: "CMS powinien odzwierciedlać typy treści i sposób pracy zespołu. Headless CMS ma sens, gdy ta sama treść zasila wiele kanałów, frontend wymaga większej swobody albo potrzebna jest separacja publikacji od renderowania. Nie wdrażamy go automatycznie, jeśli prostszy model wystarcza.",
    capabilities: ["Content model", "Headless", "Editorial UX", "Roles", "Preview", "API", "Localization", "Migration"],
    outcomes: [
      { title: "Bezpieczna edycja", description: "Redaktor zmienia treść w kontrolowanych polach zamiast przypadkowo modyfikować strukturę strony." },
      { title: "Spójne dane", description: "Powtarzalne typy treści mają wspólny model i mogą być wykorzystywane w wielu miejscach." },
      { title: "Łatwiejszy rozwój", description: "Frontend i model treści mogą ewoluować niezależnie, jeśli architektura tego wymaga." },
    ],
    deliverables: [
      { index: "01", title: "Content model", description: "Typy treści, pola, relacje i wymagane walidacje.", tags: ["Content", "Schema", "Relations", "Validation"] },
      { index: "02", title: "Editorial workflow", description: "Role, draft, preview, publikacja i zasady zmian.", tags: ["Roles", "Preview", "Workflow", "Governance"] },
      { index: "03", title: "Frontend integration", description: "Pobieranie, renderowanie, cache i obsługa brakujących danych.", tags: ["API", "Frontend", "Cache", "Fallback"] },
      { index: "04", title: "Migration", description: "Przeniesienie istniejących treści z kontrolą adresów i jakości danych.", tags: ["Migration", "SEO", "URLs", "QA"] },
    ],
    process: [
      { title: "Inventory", description: "Sprawdzamy typy treści i sposób ich aktualizacji." },
      { title: "Model", description: "Definiujemy struktury i relacje danych." },
      { title: "Integration", description: "Łączymy CMS z frontendem i preview." },
      { title: "Editorial QA", description: "Testujemy publikację, role i typowe błędy redakcyjne." },
    ],
    faqs: [
      { question: "Czy headless CMS jest zawsze lepszy od klasycznego?", answer: "Nie. Jest lepszy wtedy, gdy separacja treści i frontendu rozwiązuje konkretny problem. Dla prostego serwisu może być zbędnym kosztem." },
      { question: "Czy można przenieść treść z WordPressa?", answer: "Tak, po inwentaryzacji struktur, mediów, URL-i i danych wymagających transformacji." },
      { question: "Czy CMS może obsługiwać wiele języków?", answer: "Tak. Model lokalizacji trzeba jednak ustalić przed wdrożeniem, szczególnie dla relacji, slugów i fallbacków językowych." },
    ],
    related: ["strony-internetowe", "uslugi/strony-wielojezyczne", "modernizacja-stron"],
  },
  pwa: {
    key: "pwa",
    slug: "uslugi/pwa",
    label: "PWA",
    pillar: "CREATE",
    code: "CREATE / PWA",
    eyebrow: "LEADFLOWAI / PROGRESSIVE WEB APP",
    title: "PWA wtedy, gdy strona ma zachowywać się bardziej jak aplikacja.",
    lead: "Dodajemy instalowalność, offline strategy, cache i funkcje aplikacyjne tam, gdzie poprawiają realny scenariusz użytkownika.",
    summary: "Progressive Web App z kontrolowanym cache, trybem offline i zachowaniem dopasowanym do urządzeń.",
    directAnswer: "PWA rozszerza aplikację webową o możliwości takie jak instalacja, service worker i kontrola cache. Nie jest substytutem aplikacji natywnej w każdym przypadku. Najpierw ustalamy, które zachowania faktycznie przynoszą wartość i jak uniknąć problemów z nieaktualną treścią lub cache.",
    capabilities: ["Service worker", "Offline", "Install", "Cache", "App shell", "Updates", "Mobile", "Fallback"],
    outcomes: [
      { title: "Szybsze powroty", description: "Kontrolowany cache może ograniczyć ponowne pobieranie stabilnych zasobów." },
      { title: "Odporność na słabą sieć", description: "Wybrane funkcje mogą zachować użyteczny stan także przy chwilowym braku połączenia." },
      { title: "Instalowalność", description: "Produkt może działać z ekranu głównego bez publikowania pełnej aplikacji natywnej, jeśli platforma to wspiera." },
    ],
    deliverables: [
      { index: "01", title: "PWA fit assessment", description: "Ocena scenariuszy, które uzasadniają service worker i instalację.", tags: ["Use case", "Scope", "Mobile", "Risk"] },
      { index: "02", title: "Caching strategy", description: "Jawne zasady cache dla shell, danych i zasobów.", tags: ["Cache", "Offline", "Updates", "Storage"] },
      { index: "03", title: "Install experience", description: "Manifest, ikony, installability i zachowanie standalone.", tags: ["Manifest", "Install", "UX", "Icons"] },
      { index: "04", title: "Offline + update QA", description: "Testy aktualizacji, błędów sieci i czyszczenia starych wersji.", tags: ["QA", "Offline", "Versioning", "Fallback"] },
    ],
    process: [
      { title: "Fit", description: "Sprawdzamy, czy PWA rozwiązuje realny problem." },
      { title: "Cache model", description: "Definiujemy co może działać offline i jak długo." },
      { title: "Build", description: "Wdrażamy manifest, worker i stany sieciowe." },
      { title: "Device QA", description: "Testujemy instalację, aktualizacje i platformowe ograniczenia." },
    ],
    faqs: [
      { question: "Czy PWA zastępuje aplikację iOS/Android?", answer: "Czasem może, ale nie zawsze. Dostęp do funkcji systemowych i zasady platform różnią się, więc wybór zależy od wymagań." },
      { question: "Czy każda strona potrzebuje service workera?", answer: "Nie. Dla wielu serwisów prosty cache HTTP jest bezpieczniejszy i wystarczający." },
      { question: "Czy PWA działa offline w całości?", answer: "Tylko jeśli konkretny zakres został tak zaprojektowany. Dane wymagające serwera lub aktualnego stanu nie powinny być udawane jako dostępne offline." },
    ],
    related: ["uslugi/aplikacje-webowe", "web-development", "uslugi/core-web-vitals"],
  },
  "strony-wielojezyczne": {
    key: "strony-wielojezyczne",
    slug: "uslugi/strony-wielojezyczne",
    label: "Strony wielojęzyczne",
    pillar: "CREATE",
    code: "CREATE / I18N",
    eyebrow: "LEADFLOWAI / MULTILINGUAL WEB",
    title: "Strony wielojęzyczne z poprawną architekturą języków, URL-i i treści.",
    lead: "Projektujemy lokalizację, routing, hreflang, fallbacki i workflow redakcyjny tak, aby kolejne języki nie tworzyły bałaganu technicznego.",
    summary: "Internationalizacja i lokalizacja połączone z routingiem, SEO i procesem publikacji.",
    directAnswer: "Wielojęzyczna strona wymaga więcej niż przetłumaczenia tekstu. Trzeba ustalić strukturę URL, wersje regionalne, hreflang, canonicale, lokalizację elementów interfejsu, fallbacki i proces aktualizacji. Dzięki temu każda wersja językowa pozostaje spójna i indeksowalna.",
    capabilities: ["i18n", "Localization", "hreflang", "Routing", "CMS", "Regional content", "SEO", "QA"],
    outcomes: [
      { title: "Jednoznaczne wersje", description: "Każdy język i rynek ma jawny adres oraz relację z pozostałymi wersjami." },
      { title: "Spójna publikacja", description: "Zmiany treści można kontrolować bez ręcznego kopiowania całych podstron." },
      { title: "Lepsza indeksacja", description: "Hreflang, canonical i sitemap opisują rzeczywistą strukturę wersji językowych." },
    ],
    deliverables: [
      { index: "01", title: "Locale architecture", description: "Języki, regiony, URL-e, domyślna wersja i fallbacki.", tags: ["Locales", "URLs", "Routing", "Fallback"] },
      { index: "02", title: "Content localization model", description: "Zasady tłumaczeń, treści regionalnych i wspólnych danych.", tags: ["Content", "CMS", "Workflow", "Regions"] },
      { index: "03", title: "Search signals", description: "Hreflang, canonical, sitemap i metadata dla każdej wersji.", tags: ["hreflang", "SEO", "Canonical", "Sitemap"] },
      { index: "04", title: "Locale QA", description: "Testy switchera, braków tłumaczeń, formatów i linkowania.", tags: ["QA", "Links", "Formats", "A11y"] },
    ],
    process: [
      { title: "Markets", description: "Ustalamy języki, regiony i różnice w ofercie." },
      { title: "Routing", description: "Projektujemy strukturę adresów i fallbacków." },
      { title: "Localization", description: "Łączymy treść i interfejs z modelem językowym." },
      { title: "Search QA", description: "Walidujemy hreflang, canonical, linki i sitemapę." },
    ],
    faqs: [
      { question: "Czy automatyczne tłumaczenie wystarczy?", answer: "Może pomóc w procesie, ale publiczna treść powinna być sprawdzona pod znaczenie, ofertę i terminologię właściwą dla rynku." },
      { question: "Czy każdy język musi mieć identyczną treść?", answer: "Nie. Lokalizacja może uwzględniać różnice rynkowe, o ile struktura jasno rozróżnia wersje." },
      { question: "Czy hreflang jest potrzebny?", answer: "Przy wielu wersjach językowych lub regionalnych zwykle jest ważnym sygnałem relacji między stronami i powinien odpowiadać faktycznym URL-om." },
    ],
    related: ["uslugi/cms-headless", "seo", "strony-internetowe"],
  },
  "architektura-informacji": {
    key: "architektura-informacji",
    slug: "uslugi/architektura-informacji",
    label: "Architektura informacji",
    pillar: "CREATE",
    code: "CREATE / IA",
    eyebrow: "LEADFLOWAI / INFORMATION ARCHITECTURE",
    title: "Architektura informacji, która porządkuje ofertę, wyszukiwanie i konwersję.",
    lead: "Układamy strukturę stron, sekcji, encji i linków tak, aby użytkownik i system wyszukiwania rozumieli ten sam model informacji.",
    summary: "Mapa informacji i relacji będąca wspólnym fundamentem UX, SEO, AEO, GEO i CRO.",
    directAnswer: "Architektura informacji określa, jakie strony i sekcje istnieją, jak są nazywane, jak łączą się między sobą i gdzie użytkownik znajdzie odpowiedź. To warstwa wcześniejsza niż design. Dobrze zaprojektowana ogranicza kanibalizację treści, poprawia nawigację i ułatwia późniejszą rozbudowę.",
    capabilities: ["IA", "Taxonomy", "Entity map", "Navigation", "Internal linking", "Intent", "Content model", "CRO"],
    outcomes: [
      { title: "Mniej duplikacji", description: "Każdy ważny temat i intencja ma jasne miejsce zamiast wielu podobnych podstron konkurujących ze sobą." },
      { title: "Lepsza nawigacja", description: "Użytkownik może przechodzić między potrzebą, usługą, dowodem i kontaktem logicznymi ścieżkami." },
      { title: "Fundament search", description: "Encje, hierarchia i internal linking tworzą spójny model dla SEO, AEO i GEO." },
    ],
    deliverables: [
      { index: "01", title: "Content inventory", description: "Lista istniejących i potrzebnych typów informacji.", tags: ["Inventory", "Content", "Pages", "Gaps"] },
      { index: "02", title: "Taxonomy + entity map", description: "Nazwy, kategorie, relacje i granice tematów.", tags: ["Taxonomy", "Entities", "Naming", "Relations"] },
      { index: "03", title: "Site map + navigation", description: "Hierarchia URL-i, menu i ścieżek użytkownika.", tags: ["Sitemap", "Navigation", "URLs", "UX"] },
      { index: "04", title: "Internal linking model", description: "Reguły łączenia usług, wiedzy, proof i CTA.", tags: ["Links", "SEO", "CRO", "Context"] },
    ],
    process: [
      { title: "Inventory", description: "Zbieramy ofertę, pytania, treści i obecne URL-e." },
      { title: "Intent", description: "Rozdzielamy potrzeby użytkowników i zakresy tematyczne." },
      { title: "Model", description: "Budujemy hierarchię oraz relacje między encjami." },
      { title: "Validation", description: "Sprawdzamy czy model wspiera UX, search i przyszły rozwój." },
    ],
    faqs: [
      { question: "Czy architektura informacji to sitemap XML?", answer: "Nie. Sitemap XML jest technicznym wykazem adresów. Architektura informacji opisuje znaczenie, hierarchię i relacje treści." },
      { question: "Czy można zrobić IA przed copywritingiem?", answer: "Tak, a zwykle warto. Najpierw wiadomo wtedy, jakie pytania i typy treści muszą zostać napisane." },
      { question: "Czy IA wpływa na SEO?", answer: "Tak. Struktura tematów, URL-i i linkowania jest jednym z fundamentów technicznego i informacyjnego SEO." },
    ],
    related: ["seo-aeo-geo", "uslugi/ux-ui-design", "uslugi/copywriting-www"],
  },
  cro: {
    key: "cro",
    slug: "uslugi/cro",
    label: "CRO",
    pillar: "CONVERT",
    code: "CONVERT / CRO",
    eyebrow: "LEADFLOWAI / CONVERSION RATE OPTIMIZATION",
    title: "CRO: optymalizacja ścieżki od intencji do działania.",
    lead: "Analizujemy komunikat, hierarchię, CTA, formularze i zachowanie użytkowników, a zmiany opieramy na hipotezach i danych zamiast przypadkowych trikach.",
    summary: "Systematyczne upraszczanie decyzji i usuwanie tarcia w krytycznych ścieżkach konwersji.",
    directAnswer: "CRO nie polega na zmianie koloru przycisku. Zaczyna się od zdefiniowania konwersji, źródeł ruchu i kroków prowadzących do działania. Następnie identyfikujemy bariery, tworzymy hipotezy i mierzymy efekty zmian, jeśli dostępny wolumen danych pozwala na wiarygodną ocenę.",
    capabilities: ["Funnel", "CTA", "Forms", "Analytics", "Hypotheses", "UX", "Copy", "Experiments"],
    outcomes: [
      { title: "Mniej tarcia", description: "Usuwamy niepotrzebne kroki, niejasne komunikaty i konflikty CTA." },
      { title: "Lepszy pomiar", description: "Konwersje i etapy ścieżki mają jawne zdarzenia zamiast jednego ogólnego wskaźnika ruchu." },
      { title: "Priorytety zmian", description: "Hipotezy są porządkowane według wpływu, dowodów i kosztu wdrożenia." },
    ],
    deliverables: [
      { index: "01", title: "Conversion map", description: "Główne i pomocnicze konwersje oraz ich zależności.", tags: ["Goals", "Funnel", "Events", "Intent"] },
      { index: "02", title: "Friction audit", description: "Bariery w treści, interfejsie, formularzach i procesie.", tags: ["UX", "Forms", "Copy", "Mobile"] },
      { index: "03", title: "Hypothesis backlog", description: "Zmiany z uzasadnieniem, priorytetem i sposobem pomiaru.", tags: ["Hypothesis", "Impact", "Effort", "Evidence"] },
      { index: "04", title: "Iteration", description: "Wdrożenie i ocena zmian na podstawie dostępnych danych.", tags: ["Analytics", "Tests", "QA", "Learning"] },
    ],
    process: [
      { title: "Goal", description: "Definiujemy co dokładnie ma być konwersją." },
      { title: "Evidence", description: "Łączymy dane ilościowe i obserwacje jakościowe." },
      { title: "Hypotheses", description: "Tworzymy możliwe przyczyny i testowalne zmiany." },
      { title: "Iterate", description: "Wdrażamy priorytety i oceniamy wynik bez udawania pewności tam, gdzie danych jest za mało." },
    ],
    faqs: [
      { question: "Czy CRO ma sens przy małym ruchu?", answer: "Tak jako audyt ścieżki i poprawa oczywistych barier, ale klasyczne testy statystyczne mogą wymagać większego wolumenu." },
      { question: "Czy CRO obejmuje formularze?", answer: "Tak. Formularze, walidacja, liczba pól, komunikaty i fallback są częścią ścieżki konwersji." },
      { question: "Czy można zagwarantować wzrost konwersji?", answer: "Nie. Można zwiększać jakość procesu optymalizacji i usuwać potwierdzone bariery, ale wynik zależy również od ruchu, oferty i rynku." },
    ],
    related: ["landing-pages", "uslugi/analityka-webowa", "uslugi/lead-generation"],
  },
  "analityka-webowa": {
    key: "analityka-webowa",
    slug: "uslugi/analityka-webowa",
    label: "Analityka webowa",
    pillar: "CONVERT",
    code: "CONVERT / ANALYTICS",
    eyebrow: "LEADFLOWAI / WEB ANALYTICS",
    title: "Analityka webowa, która odpowiada na pytania biznesowe.",
    lead: "Projektujemy plan pomiaru, zdarzenia, konwersje i dashboardy tak, aby dane wynikały z decyzji, które firma rzeczywiście podejmuje.",
    summary: "Measurement plan, event taxonomy, konwersje i raportowanie bez zbierania danych dla samego zbierania.",
    directAnswer: "Analityka zaczyna się od pytania: jakiej decyzji mają służyć dane? Dopiero potem definiujemy zdarzenia, parametry, konwersje i raporty. Zakres może obejmować konfigurację narzędzi, warstwę zgód, walidację eventów oraz dokumentację potrzebną do utrzymania pomiaru.",
    capabilities: ["Measurement plan", "Events", "Conversions", "GA4", "Tagging", "Dashboards", "Consent", "QA"],
    outcomes: [
      { title: "Mniej szumu", description: "Zbierane są zdarzenia powiązane z realnymi pytaniami, a nie każdy możliwy klik." },
      { title: "Spójne nazewnictwo", description: "Eventy i parametry mają wspólną taksonomię, dzięki czemu raporty można interpretować." },
      { title: "Wiarygodniejszy pomiar", description: "Walidujemy duplikaty, brakujące eventy i wpływ zgód na dostępne dane." },
    ],
    deliverables: [
      { index: "01", title: "Measurement plan", description: "Cele, KPI, zdarzenia i parametry powiązane z decyzjami biznesowymi.", tags: ["KPI", "Events", "Goals", "Taxonomy"] },
      { index: "02", title: "Implementation", description: "Konfiguracja pomiaru zgodnie z używanym stackiem i zgodami.", tags: ["GA4", "Tags", "Consent", "Data"] },
      { index: "03", title: "Validation", description: "Testy eventów, duplikatów, parametrów i konwersji.", tags: ["Debug", "QA", "Events", "Conversions"] },
      { index: "04", title: "Reporting", description: "Raport lub dashboard odpowiadający na wcześniej zdefiniowane pytania.", tags: ["Dashboard", "Reporting", "Funnel", "Insights"] },
    ],
    process: [
      { title: "Questions", description: "Ustalamy decyzje, które mają wspierać dane." },
      { title: "Plan", description: "Definiujemy taksonomię eventów i parametrów." },
      { title: "Implement", description: "Wdrażamy pomiar i zależności consent." },
      { title: "Validate", description: "Porównujemy oczekiwane i rzeczywiste zdarzenia." },
    ],
    faqs: [
      { question: "Czy zawsze potrzebny jest Google Analytics?", answer: "Nie. Narzędzie dobieramy do potrzeb pomiaru, prywatności i możliwości technicznych projektu." },
      { question: "Czy możecie mierzyć wysłanie formularza?", answer: "Tak, o ile zdarzenie jest możliwe do wiarygodnego wykrycia i zgodne z przyjętym modelem danych." },
      { question: "Czy analytics zastępuje badania użytkowników?", answer: "Nie. Dane ilościowe pokazują co się wydarzyło, ale nie zawsze wyjaśniają dlaczego. Oba źródła mogą się uzupełniać." },
    ],
    related: ["uslugi/cro", "uslugi/lead-generation", "landing-pages"],
  },
  "lead-generation": {
    key: "lead-generation",
    slug: "uslugi/lead-generation",
    label: "Lead generation WWW",
    pillar: "CONVERT",
    code: "CONVERT / LEADS",
    eyebrow: "LEADFLOWAI / LEAD GENERATION",
    title: "System pozyskiwania leadów zbudowany wokół jakości zapytania.",
    lead: "Łączymy stronę, ofertę, formularze, kwalifikację, tracking i przekazanie danych tak, aby kontakt był użyteczny dla obu stron.",
    summary: "Ścieżka od źródła ruchu do kwalifikowanego zapytania i bezpiecznego przekazania leadu.",
    directAnswer: "Lead generation na stronie obejmuje więcej niż formularz. Projektujemy punkt wejścia, argumentację, CTA, zakres danych, walidację, zgodę, potwierdzenie i sposób przekazania zapytania. Jeśli potrzebna jest kwalifikacja, pytania muszą pomagać ocenić projekt bez niepotrzebnego obciążania użytkownika.",
    capabilities: ["Lead funnel", "Forms", "Qualification", "Validation", "Consent", "CRM", "Email", "Tracking"],
    outcomes: [
      { title: "Lepszy kontekst", description: "Zapytanie zawiera informacje potrzebne do kolejnego kroku zamiast pustego „proszę o kontakt”." },
      { title: "Mniej utraconych leadów", description: "Obsługa błędów, potwierdzenia i fallback zmniejszają ryzyko niewidocznej awarii formularza." },
      { title: "Mierzalna ścieżka", description: "Można rozróżnić wejście, rozpoczęcie formularza, wysłanie i dalszy etap procesu." },
    ],
    deliverables: [
      { index: "01", title: "Lead path", description: "Źródła ruchu, strony wejścia, CTA i moment kwalifikacji.", tags: ["Funnel", "Intent", "CTA", "CRO"] },
      { index: "02", title: "Form architecture", description: "Pola, warunki, walidacja, komunikaty i ochrona przed nadużyciami.", tags: ["Forms", "Validation", "Security", "UX"] },
      { index: "03", title: "Delivery", description: "E-mail, CRM, webhook lub inny kontrolowany kanał przekazania danych.", tags: ["CRM", "Email", "Webhook", "Fallback"] },
      { index: "04", title: "Tracking", description: "Zdarzenia i konwersje dla kolejnych etapów lead funnel.", tags: ["Events", "Analytics", "Conversion", "QA"] },
    ],
    process: [
      { title: "Qualification", description: "Ustalamy, jakie dane są faktycznie potrzebne." },
      { title: "UX", description: "Projektujemy formularz i stany odpowiedzi." },
      { title: "Delivery", description: "Łączymy bezpieczny kanał odbioru." },
      { title: "Monitoring", description: "Testujemy i obserwujemy krytyczny przepływ po uruchomieniu." },
    ],
    faqs: [
      { question: "Czy formularz powinien mieć dużo pól?", answer: "Tylko tyle, ile uzasadnia kolejny etap procesu. Każde dodatkowe pole musi mieć konkretną wartość operacyjną." },
      { question: "Czy lead może trafiać do CRM?", answer: "Tak, jeśli CRM udostępnia odpowiednią integrację i zakres danych jest zgodny z procesem oraz polityką prywatności." },
      { question: "Czy można użyć tylko mailto zamiast formularza?", answer: "Tak. Dla prostych stron bez backendu bezpośredni e-mail może być bardziej niezawodnym i adekwatnym rozwiązaniem." },
    ],
    related: ["uslugi/cro", "uslugi/integracje-crm", "uslugi/analityka-webowa"],
  },
  "copywriting-www": {
    key: "copywriting-www",
    slug: "uslugi/copywriting-www",
    label: "Content i copywriting WWW",
    pillar: "CONVERT",
    code: "CONVERT / CONTENT",
    eyebrow: "LEADFLOWAI / CONTENT + COPY",
    title: "Treść WWW zbudowana wokół intencji, decyzji i publicznej prawdy.",
    lead: "Tworzymy strukturę komunikatu, odpowiedzi, sekcje usługowe i treści informacyjne, które wspierają UX, SEO, AEO, GEO i sprzedaż bez pustych sloganów.",
    summary: "Message architecture, answer-first copy, proof context i treść źródłowa dla ludzi oraz systemów wyszukiwania.",
    directAnswer: "Copy na stronę powinno odpowiadać na pytania użytkownika, wyjaśniać zakres i ograniczenia oraz prowadzić do kolejnego działania. W LeadFlowAI treść projektujemy razem z architekturą informacji i search architecture, dzięki czemu nie tworzymy osobnej wersji tekstu „dla SEO”.",
    capabilities: ["Message architecture", "Service copy", "Answer-first", "SEO content", "AEO", "GEO", "Proof", "Editorial"],
    outcomes: [
      { title: "Szybsze zrozumienie", description: "Najważniejsza odpowiedź pojawia się wcześniej, a rozwinięcie dostarcza kontekstu potrzebnego do decyzji." },
      { title: "Spójne pozycjonowanie", description: "Nazwy usług, zakres i relacja marki z operatorem są konsekwentne w całym serwisie." },
      { title: "Lepsza baza search", description: "Treść ma wyraźne tematy, definicje i relacje zamiast sztucznego powtarzania fraz." },
    ],
    deliverables: [
      { index: "01", title: "Message architecture", description: "Główna obietnica, odbiorca, obiekcje, dowody i CTA.", tags: ["Message", "Offer", "CRO", "UX"] },
      { index: "02", title: "Page copy", description: "Treść sekcji, usług, odpowiedzi i mikrocopy interfejsu.", tags: ["Copy", "Pages", "Microcopy", "Answers"] },
      { index: "03", title: "Search alignment", description: "Dopasowanie tematów, intencji, nagłówków i internal linking bez keyword stuffing.", tags: ["SEO", "AEO", "GEO", "Intent"] },
      { index: "04", title: "Editorial QA", description: "Spójność faktów, nazw, linków, CTA i public truth przed publikacją.", tags: ["QA", "Truth", "Consistency", "Links"] },
    ],
    process: [
      { title: "Source", description: "Zbieramy fakty, ofertę, ograniczenia i realne dowody." },
      { title: "Structure", description: "Układamy informację zgodnie z intencją strony." },
      { title: "Write", description: "Tworzymy copy i odpowiedzi w docelowej hierarchii." },
      { title: "Review", description: "Weryfikujemy sens, spójność i brak nieudowodnionych claimów." },
    ],
    faqs: [
      { question: "Czy copywriting obejmuje teksty pod SEO?", answer: "Tak, ale nie tworzymy sztucznej warstwy słów kluczowych. Temat, intencja i semantyka są częścią tej samej treści dla użytkownika." },
      { question: "Czy możecie pisać na podstawie krótkiego briefu?", answer: "Możemy rozpocząć od briefu, ale fakty i zakres oferty wymagają potwierdzenia, szczególnie przy treściach eksperckich lub prawnych." },
      { question: "Czy content może wspierać AEO i GEO?", answer: "Tak. Jasne odpowiedzi, entity clarity, kontekst źródłowy i spójne fakty są wspólnym fundamentem tych warstw." },
    ],
    related: ["uslugi/architektura-informacji", "seo-aeo-geo", "uslugi/cro"],
  },
  "integracje-ai": {
    key: "integracje-ai",
    slug: "uslugi/integracje-ai",
    label: "Integracje AI",
    pillar: "INTELLIGENCE",
    code: "INTELLIGENCE / AI",
    eyebrow: "LEADFLOWAI / INTEGRACJE AI",
    title: "Integracje AI w procesie WWW z kontrolą danych, źródeł i fallbacku.",
    lead: "Łączymy modele AI z formularzami, wyszukiwaniem, treścią lub procesem operacyjnym tam, gdzie wynik można ograniczyć i sensownie zweryfikować.",
    summary: "AI jako kontrolowany komponent systemu, a nie nieograniczony generator odpowiedzi.",
    directAnswer: "Integracja AI powinna mieć jasno zdefiniowane wejście, rolę, źródła, uprawnienia i fallback. Projektujemy warstwę serwerową, limity, walidację oraz sposób obsługi błędów tak, aby awaria providera lub niepewna odpowiedź nie blokowała podstawowej funkcji strony.",
    capabilities: ["LLM API", "Guardrails", "Structured output", "Tools", "Fallback", "Rate limits", "Privacy", "Monitoring"],
    outcomes: [
      { title: "AI z konkretną rolą", description: "Model wykonuje określone zadanie zamiast być ogólnym dodatkiem do interfejsu." },
      { title: "Kontrolowane dane", description: "Zakres wejścia i wyjścia jest jawny, a sekrety providerów nie trafiają do przeglądarki." },
      { title: "Odporność", description: "Fallback i obsługa timeoutów pozwalają zachować podstawowy proces bez AI." },
    ],
    deliverables: [
      { index: "01", title: "Use-case contract", description: "Rola modelu, wejścia, wyjścia, ograniczenia i kryteria fallbacku.", tags: ["Scope", "Inputs", "Outputs", "Safety"] },
      { index: "02", title: "Server integration", description: "Provider, sekrety, limity, walidacja i obsługa błędów po stronie serwera.", tags: ["API", "Secrets", "Rate limit", "Validation"] },
      { index: "03", title: "UX + fallback", description: "Stany oczekiwania, błędu, braku pewności i przekazania do człowieka.", tags: ["UX", "Fallback", "Errors", "A11y"] },
      { index: "04", title: "Observability", description: "Bezpieczne logowanie zdarzeń potrzebnych do diagnozy jakości i awarii.", tags: ["Monitoring", "Logs", "Quality", "Privacy"] },
    ],
    process: [
      { title: "Use case", description: "Oddzielamy realne zadanie od atrakcyjnej demonstracji AI." },
      { title: "Contract", description: "Definiujemy dane, granice i fallback." },
      { title: "Integration", description: "Wdrażamy serwerową komunikację i interfejs." },
      { title: "Adversarial QA", description: "Testujemy błędne wejścia, timeouty i odpowiedzi poza zakresem." },
    ],
    faqs: [
      { question: "Czy klucz API może być w frontendzie?", answer: "Nie powinien. Sekrety providera przechowujemy po stronie serwerowej lub w bezpiecznej warstwie infrastruktury." },
      { question: "Czy integracja AI musi działać zawsze?", answer: "Nie. Jeżeli AI jest warstwą pomocniczą, projektujemy fallback tak, aby podstawowy proces nadal działał." },
      { question: "Czy można wymusić format odpowiedzi?", answer: "W wielu przypadkach można ograniczać strukturę wyjścia, ale nadal trzeba walidować wynik i obsługiwać błędy." },
    ],
    related: ["chatboty-ai", "uslugi/rag-dla-stron", "uslugi/automatyzacje-www"],
  },
  "rag-dla-stron": {
    key: "rag-dla-stron",
    slug: "uslugi/rag-dla-stron",
    label: "RAG dla stron i wiedzy",
    pillar: "INTELLIGENCE",
    code: "INTELLIGENCE / RAG",
    eyebrow: "LEADFLOWAI / RAG + KNOWLEDGE",
    title: "RAG dla stron i baz wiedzy oparty na zatwierdzonych źródłach.",
    lead: "Budujemy retrieval nad dokumentacją, ofertą i wiedzą, żeby model mógł korzystać z kontrolowanego kontekstu zamiast odpowiadać wyłącznie z pamięci modelu.",
    summary: "Ingest, chunking, retrieval, ranking, cytowalny kontekst i guardrails dla wiedzy firmy.",
    directAnswer: "RAG łączy wyszukiwanie w zatwierdzonych źródłach z generowaniem odpowiedzi. Jego jakość zależy od danych, chunkingu, retrievalu, rankingowania i sposobu przekazania kontekstu do modelu. Dlatego testujemy nie tylko finalną odpowiedź, ale również to, czy system znalazł właściwe źródło.",
    capabilities: ["Ingestion", "Chunking", "Embeddings", "Retrieval", "Reranking", "Citations", "Guardrails", "Evaluation"],
    outcomes: [
      { title: "Źródłowy kontekst", description: "Model odpowiada na podstawie dokumentów dostępnych w kontrolowanej bazie wiedzy." },
      { title: "Lepsza diagnostyka", description: "Można oddzielić błąd retrievalu od błędu generowania odpowiedzi." },
      { title: "Aktualizowalna wiedza", description: "Zmiana dokumentu nie wymaga trenowania całego modelu od początku." },
    ],
    deliverables: [
      { index: "01", title: "Knowledge inventory", description: "Źródła, formaty, zasady aktualizacji i zakres publikowalnych danych.", tags: ["Sources", "Data", "Governance", "Privacy"] },
      { index: "02", title: "Retrieval pipeline", description: "Ingest, chunking, embeddings, indeks i ranking.", tags: ["Chunks", "Embeddings", "Search", "Rerank"] },
      { index: "03", title: "Answer layer", description: "Prompt contract, kontekst, odpowiedź, cytowanie i fallback.", tags: ["Context", "Citations", "Prompt", "Fallback"] },
      { index: "04", title: "Evaluation", description: "Zestaw pytań kontrolnych i pomiar jakości retrievalu oraz odpowiedzi.", tags: ["Eval", "Recall", "Quality", "Regression"] },
    ],
    process: [
      { title: "Sources", description: "Wybieramy zatwierdzone dane i granice public truth." },
      { title: "Retrieval", description: "Budujemy i stroimy wyszukiwanie kontekstu." },
      { title: "Generation", description: "Łączymy kontekst z modelem i fallbackiem." },
      { title: "Evaluation", description: "Testujemy pytania proste, graniczne i brak odpowiedzi w źródłach." },
    ],
    faqs: [
      { question: "Czy RAG eliminuje halucynacje?", answer: "Nie całkowicie. Dostarcza lepszy kontekst i umożliwia kontrolę źródeł, ale wynik nadal trzeba projektować z fallbackiem i walidacją." },
      { question: "Czy każda baza wiedzy potrzebuje embeddings?", answer: "Nie zawsze. Dla małego lub bardzo ustrukturyzowanego zbioru prostsze wyszukiwanie może być wystarczające." },
      { question: "Czy dokumenty mogą być aktualizowane?", answer: "Tak. Pipeline powinien jawnie obsługiwać dodawanie, zmianę i usuwanie źródeł oraz ponowne indeksowanie." },
    ],
    related: ["chatboty-ai", "uslugi/integracje-ai", "uslugi/copywriting-www"],
  },
  "integracje-api": {
    key: "integracje-api",
    slug: "uslugi/integracje-api",
    label: "Integracje API",
    pillar: "CONNECT",
    code: "CONNECT / API",
    eyebrow: "LEADFLOWAI / INTEGRACJE API",
    title: "Integracje API z kontrolą kontraktu, błędów i bezpieczeństwa.",
    lead: "Łączymy stronę lub aplikację z zewnętrznymi systemami przez API, webhooks i kolejki, projektując także retry, idempotency i obserwowalność.",
    summary: "Stabilne połączenia systemów oparte na jawnych kontraktach danych i obsłudze awarii.",
    directAnswer: "Integracja API nie kończy się na poprawnym żądaniu HTTP. Trzeba zdefiniować kontrakt danych, autoryzację, timeout, retry, idempotency, limity i zachowanie podczas częściowej awarii. Dzięki temu błąd zewnętrznego systemu nie prowadzi do cichej utraty danych.",
    capabilities: ["REST", "GraphQL", "Webhooks", "Auth", "Retry", "Idempotency", "Queues", "Observability"],
    outcomes: [
      { title: "Mniej ręcznego przepisywania", description: "Dane mogą przepływać między systemami według jawnych reguł." },
      { title: "Kontrolowane błędy", description: "Timeout i błąd providera mają przewidywalne zachowanie oraz możliwość ponowienia." },
      { title: "Lepsza diagnostyka", description: "Logi techniczne pozwalają ustalić etap, na którym integracja przestała działać." },
    ],
    deliverables: [
      { index: "01", title: "API contract", description: "Endpointy, payloady, autoryzacja i ograniczenia providera.", tags: ["Contract", "Payload", "Auth", "Limits"] },
      { index: "02", title: "Integration layer", description: "Transformacja danych, wywołania, webhooks i zależności.", tags: ["API", "Webhook", "Transform", "Server"] },
      { index: "03", title: "Reliability", description: "Timeout, retry, idempotency i obsługa częściowych błędów.", tags: ["Retry", "Idempotency", "Queue", "Fallback"] },
      { index: "04", title: "Monitoring", description: "Logi i sygnały potrzebne do wykrywania awarii integracji.", tags: ["Logs", "Errors", "Monitoring", "QA"] },
    ],
    process: [
      { title: "Contract review", description: "Sprawdzamy dokumentację i ograniczenia obu systemów." },
      { title: "Data map", description: "Mapujemy pola, statusy i transformacje." },
      { title: "Build", description: "Wdrażamy połączenie i obsługę błędów." },
      { title: "Failure QA", description: "Testujemy timeouty, duplikaty i nieprawidłowe payloady." },
    ],
    faqs: [
      { question: "Czy można zintegrować dowolne dwa systemy?", answer: "Tylko jeśli udostępniają potrzebny interfejs lub inny dozwolony mechanizm wymiany danych." },
      { question: "Czy webhook może się zgubić?", answer: "Może wystąpić błąd dostarczenia. Dlatego krytyczne integracje projektujemy z retry, idempotency i możliwością audytu." },
      { question: "Czy klucze API są przechowywane w frontendzie?", answer: "Sekrety nie powinny trafiać do publicznego kodu przeglądarki. Umieszczamy je w odpowiedniej warstwie serwerowej/infrastrukturalnej." },
    ],
    related: ["web-development", "uslugi/automatyzacje-www", "uslugi/integracje-crm"],
  },
  "automatyzacje-www": {
    key: "automatyzacje-www",
    slug: "uslugi/automatyzacje-www",
    label: "Automatyzacje WWW",
    pillar: "CONNECT",
    code: "CONNECT / AUTOMATION",
    eyebrow: "LEADFLOWAI / AUTOMATYZACJE WWW",
    title: "Automatyzacje WWW, które przenoszą dane bez ręcznego kopiowania.",
    lead: "Łączymy formularze, e-mail, CRM, dokumenty, kalendarze i API w kontrolowane workflow z logami, retry i punktami zatwierdzenia.",
    summary: "Workflow od zdarzenia na stronie do kolejnych działań operacyjnych z kontrolą błędów.",
    directAnswer: "Automatyzacja powinna mieć jawny trigger, dane wejściowe, kolejne kroki, warunki, retry i właściciela wyjątku. Projektujemy proces tak, aby błąd jednego kroku nie wyglądał jak sukces całego workflow i aby krytyczne działania można było audytować.",
    capabilities: ["Webhooks", "n8n", "Make", "Email", "CRM", "Documents", "Approvals", "Monitoring"],
    outcomes: [
      { title: "Mniej pracy ręcznej", description: "Powtarzalne przenoszenie danych i powiadomienia mogą uruchamiać się automatycznie." },
      { title: "Jawne wyjątki", description: "Nieudane kroki są widoczne i mogą trafić do kolejki lub człowieka zamiast znikać." },
      { title: "Spójniejszy proces", description: "Reguły działania są zapisane w workflow zamiast zależeć od pamięci pojedynczej osoby." },
    ],
    deliverables: [
      { index: "01", title: "Workflow map", description: "Trigger, dane, warunki, kroki, właściciele i wyjątki.", tags: ["Trigger", "Steps", "Rules", "Owners"] },
      { index: "02", title: "Automation build", description: "Implementacja workflow w dobranym narzędziu lub kodzie.", tags: ["n8n", "Make", "Code", "Webhook"] },
      { index: "03", title: "Error handling", description: "Retry, deduplikacja, alerty i ścieżka ręcznej interwencji.", tags: ["Retry", "Errors", "Alerts", "Fallback"] },
      { index: "04", title: "Runbook", description: "Dokumentacja działania i sposobu diagnozy typowych błędów.", tags: ["Docs", "Operations", "Logs", "Recovery"] },
    ],
    process: [
      { title: "Process", description: "Rozpisujemy obecny przebieg i ręczne punkty." },
      { title: "Boundaries", description: "Wybieramy co automatyzować, a co wymaga zatwierdzenia." },
      { title: "Build", description: "Łączymy systemy i obsługę wyjątków." },
      { title: "Run QA", description: "Testujemy sukces, duplikaty, błędy i recovery." },
    ],
    faqs: [
      { question: "Czy automatyzacja może działać bez n8n lub Make?", answer: "Tak. Przy prostym lub krytycznym procesie lepsza może być własna logika serwerowa. Narzędzie dobieramy do wymagań." },
      { question: "Czy wszystko warto automatyzować?", answer: "Nie. Decyzje wymagające kontekstu, odpowiedzialności lub wysokiego ryzyka często powinny zachować krok zatwierdzenia." },
      { question: "Czy automatyzacje wymagają monitoringu?", answer: "Tak, jeśli błąd może prowadzić do utraty leadu, danych lub ważnego działania operacyjnego." },
    ],
    related: ["uslugi/integracje-api", "uslugi/integracje-crm", "uslugi/lead-generation"],
  },
  "integracje-crm": {
    key: "integracje-crm",
    slug: "uslugi/integracje-crm",
    label: "Integracje CRM",
    pillar: "CONNECT",
    code: "CONNECT / CRM",
    eyebrow: "LEADFLOWAI / CRM INTEGRATIONS",
    title: "Integracje CRM od formularza do kontrolowanego rekordu i follow-upu.",
    lead: "Projektujemy przepływ leadów, mapowanie pól, deduplikację, statusy i automatyczne działania tak, aby CRM odzwierciedlał rzeczywisty proces sprzedaży.",
    summary: "Połączenie strony z CRM z mapą danych, deduplikacją, statusami i obsługą błędów.",
    directAnswer: "Integracja CRM powinna ustalić, które dane trafiają do systemu, kiedy powstaje nowy kontakt lub szansa, jak obsługiwać duplikaty i co dzieje się po błędzie. Nie kopiujemy wszystkich pól formularza bez modelu sprzedaży; mapowanie wynika z procesu.",
    capabilities: ["CRM", "Lead routing", "Field mapping", "Deduplication", "Pipeline", "Webhooks", "Automation", "Audit"],
    outcomes: [
      { title: "Spójne rekordy", description: "Pola i statusy są mapowane według jednego modelu zamiast przypadkowego importu." },
      { title: "Szybszy follow-up", description: "Nowe zapytanie może uruchomić właściwe zadanie lub powiadomienie bez ręcznego przeklejania danych." },
      { title: "Mniej duplikatów", description: "Reguły identyfikacji i aktualizacji rekordów ograniczają niekontrolowane mnożenie kontaktów." },
    ],
    deliverables: [
      { index: "01", title: "CRM data map", description: "Pola, identyfikatory, źródła i statusy wymagane w procesie.", tags: ["Fields", "IDs", "Pipeline", "Source"] },
      { index: "02", title: "Lead routing", description: "Reguły tworzenia, aktualizacji i przypisywania rekordów.", tags: ["Routing", "Owners", "Status", "Rules"] },
      { index: "03", title: "Integration", description: "API, webhook lub automation layer z walidacją i retry.", tags: ["API", "Webhook", "Retry", "Validation"] },
      { index: "04", title: "Audit + QA", description: "Testy duplikatów, błędnych danych i ścieżki recovery.", tags: ["Dedup", "QA", "Logs", "Recovery"] },
    ],
    process: [
      { title: "Pipeline", description: "Rozpisujemy rzeczywisty proces od zapytania do kolejnego etapu." },
      { title: "Data", description: "Mapujemy minimalny potrzebny zestaw pól." },
      { title: "Integration", description: "Wdrażamy routing i automatyczne kroki." },
      { title: "Failure QA", description: "Testujemy duplikaty, timeout i niepełne dane." },
    ],
    faqs: [
      { question: "Czy integrujecie konkretny CRM?", answer: "Możemy integrować system, jeśli ma odpowiednie API, webhooki lub wspierany mechanizm automatyzacji. Zakres zależy od jego możliwości." },
      { question: "Czy każdy formularz musi tworzyć nowy kontakt?", answer: "Nie. Często lepiej najpierw sprawdzić istniejący rekord i zaktualizować go według ustalonych reguł." },
      { question: "Czy CRM może odesłać status do strony?", answer: "Tak, jeśli przypadek użycia tego wymaga i API systemu pozwala na bezpieczny przepływ w drugą stronę." },
    ],
    related: ["uslugi/lead-generation", "uslugi/automatyzacje-www", "uslugi/integracje-api"],
  },
  "core-web-vitals": {
    key: "core-web-vitals",
    slug: "uslugi/core-web-vitals",
    label: "Core Web Vitals",
    pillar: "CARE",
    code: "CARE / CWV",
    eyebrow: "LEADFLOWAI / CORE WEB VITALS",
    title: "Core Web Vitals i performance optymalizowane na podstawie pomiaru.",
    lead: "Diagnozujemy LCP, INP, CLS, koszt JavaScript, obrazy, fonty i rendering, a poprawki dobieramy do rzeczywistego bottlenecku.",
    summary: "Pomiar laboratoryjny i terenowy, identyfikacja bottlenecków i techniczna optymalizacja wydajności.",
    directAnswer: "Optymalizacja Core Web Vitals zaczyna się od pomiaru. LCP, INP i CLS mają różne przyczyny, dlatego nie stosujemy jednej listy trików do każdej strony. Analizujemy krytyczne zasoby, JavaScript, layout, obrazy, cache i zachowanie komponentów, a następnie sprawdzamy czy zmiana faktycznie poprawiła problem.",
    capabilities: ["LCP", "INP", "CLS", "JS cost", "Images", "Fonts", "Caching", "Runtime"],
    outcomes: [
      { title: "Szybszy krytyczny render", description: "Priorytetyzujemy zasoby i elementy mające realny wpływ na początkowy widok." },
      { title: "Mniejszy koszt interakcji", description: "Ograniczamy długie zadania i zbędny JavaScript tam, gdzie obciążają główny wątek." },
      { title: "Stabilniejszy layout", description: "Rezerwujemy przestrzeń i kontrolujemy dynamiczne elementy powodujące nieoczekiwane przesunięcia." },
    ],
    deliverables: [
      { index: "01", title: "Performance baseline", description: "Pomiar laboratoryjny, dostępne field data i lista krytycznych zasobów.", tags: ["Lighthouse", "CWV", "Field", "Baseline"] },
      { index: "02", title: "Bottleneck map", description: "Przyczyny kosztu renderowania, sieci i interakcji.", tags: ["Network", "JS", "Images", "Layout"] },
      { index: "03", title: "Optimization", description: "Zmiany kodu, assetów, cache lub loading strategy dopasowane do problemu.", tags: ["Code", "Cache", "Lazy", "Priority"] },
      { index: "04", title: "Regression guard", description: "Budżety i testy chroniące przed ponownym wzrostem kosztu.", tags: ["Budget", "CI", "Regression", "QA"] },
    ],
    process: [
      { title: "Measure", description: "Zbieramy before-state i rozdzielamy lab od field data." },
      { title: "Diagnose", description: "Identyfikujemy przyczynę zamiast leczyć sam wynik." },
      { title: "Optimize", description: "Wdrażamy zmiany o największym uzasadnionym wpływie." },
      { title: "Verify", description: "Porównujemy po zmianie i ustawiamy regresję." },
    ],
    faqs: [
      { question: "Czy Lighthouse 100 oznacza szybki serwis?", answer: "Nie zawsze. Lighthouse jest użytecznym testem laboratoryjnym, ale wynik zależy od warunków i nie zastępuje danych terenowych." },
      { question: "Czy animacje zawsze psują CWV?", answer: "Nie. Problemem jest koszt implementacji i wpływ na layout lub główny wątek, a nie sam fakt ruchu." },
      { question: "Czy można zagwarantować konkretne CWV dla każdego użytkownika?", answer: "Nie, bo urządzenia i sieci się różnią. Można jednak kontrolować własny kod, zasoby i regresję wydajności." },
    ],
    related: ["audyt-strony", "uslugi/hosting-deploy", "uslugi/utrzymanie-stron"],
  },
  "wcag-dostepnosc": {
    key: "wcag-dostepnosc",
    slug: "uslugi/wcag-dostepnosc",
    label: "WCAG i dostępność",
    pillar: "CARE",
    code: "CARE / WCAG",
    eyebrow: "LEADFLOWAI / WCAG + ACCESSIBILITY",
    title: "Dostępność WWW projektowana w strukturze, interakcji i treści.",
    lead: "Audytujemy i poprawiamy semantykę, klawiaturę, focus, kontrast, formularze, ruch i komunikaty zgodnie z wymaganiami właściwymi dla projektu.",
    summary: "Dostępność jako część architektury interfejsu i QA, nie końcowy plugin.",
    directAnswer: "Dostępność wymaga poprawnego HTML, logicznej kolejności, obsługi klawiatury, widocznego focusu, czytelnego kontrastu, opisów i poprawnych komunikatów. Automatyczne skanery pomagają wykryć część problemów, ale nie zastępują testowania realnych interakcji i kontekstu treści.",
    capabilities: ["Semantic HTML", "Keyboard", "Focus", "Contrast", "Forms", "ARIA", "Reduced motion", "Audit"],
    outcomes: [
      { title: "Obsługa bez myszy", description: "Krytyczne funkcje można przejść klawiaturą z widocznym i logicznym focusem." },
      { title: "Lepsza semantyka", description: "Elementy interfejsu używają właściwych struktur zamiast symulować przyciski i nagłówki." },
      { title: "Mniej barier", description: "Formularze, komunikaty i ruch uwzględniają różne sposoby korzystania ze strony." },
    ],
    deliverables: [
      { index: "01", title: "Accessibility audit", description: "Automatyczne i manualne sprawdzenie krytycznych kryteriów w ustalonym zakresie.", tags: ["WCAG", "Audit", "Keyboard", "Semantics"] },
      { index: "02", title: "Issue mapping", description: "Problemy powiązane z kryteriami, wpływem i komponentami.", tags: ["Criteria", "Impact", "Components", "Priority"] },
      { index: "03", title: "Remediation", description: "Poprawki struktury, interakcji, formularzy i stylów.", tags: ["HTML", "ARIA", "Focus", "Forms"] },
      { index: "04", title: "Regression", description: "Test powtórny i zasady zapobiegające powrotowi błędów.", tags: ["QA", "Regression", "Docs", "Components"] },
    ],
    process: [
      { title: "Scope", description: "Ustalamy wymagany poziom i krytyczne user journeys." },
      { title: "Audit", description: "Łączymy skanowanie i testy manualne." },
      { title: "Fix", description: "Poprawiamy problemy według wpływu i zależności." },
      { title: "Retest", description: "Weryfikujemy poprawki i regresję." },
    ],
    faqs: [
      { question: "Czy overlay/plugin zapewnia zgodność z WCAG?", answer: "Nie można zakładać, że pojedyncza nakładka naprawi strukturę, klawiaturę, semantykę i wszystkie problemy interakcji." },
      { question: "Czy automatyczny audyt wystarczy?", answer: "Nie. Część kryteriów wymaga oceny kontekstu oraz manualnego przejścia interfejsu." },
      { question: "Czy dostępność wpływa na design?", answer: "Może wymagać korekt kontrastu, focusu, ruchu lub interakcji, ale celem jest zachowanie charakteru projektu przy usunięciu barier." },
    ],
    related: ["uslugi/ux-ui-design", "audyt-strony", "uslugi/core-web-vitals"],
  },
  "bezpieczenstwo-stron": {
    key: "bezpieczenstwo-stron",
    slug: "uslugi/bezpieczenstwo-stron",
    label: "Bezpieczeństwo stron",
    pillar: "CARE",
    code: "CARE / SECURITY",
    eyebrow: "LEADFLOWAI / WEB SECURITY",
    title: "Bezpieczeństwo strony od powierzchni ataku po bezpieczne wdrożenie.",
    lead: "Przeglądamy sekrety, formularze, nagłówki, zależności, uprawnienia, integracje i konfigurację wdrożenia w zakresie adekwatnym do systemu.",
    summary: "Redukcja podstawowych ryzyk aplikacyjnych i operacyjnych bez obiecywania absolutnego bezpieczeństwa.",
    directAnswer: "Bezpieczeństwo WWW obejmuje kod, konfigurację, sekrety, uprawnienia, formularze, integracje i proces aktualizacji. Zakres zależy od architektury. Strona statyczna ma inne ryzyka niż aplikacja z logowaniem i bazą danych, dlatego zaczynamy od modelu powierzchni ataku i danych, które system faktycznie przetwarza.",
    capabilities: ["Secrets", "Headers", "Forms", "Auth", "Dependencies", "Rate limits", "CSP", "Hardening"],
    outcomes: [
      { title: "Mniej ekspozycji", description: "Sekrety i funkcje serwerowe są oddzielone od publicznego frontendu zgodnie z architekturą." },
      { title: "Kontrola wejścia", description: "Formularze i API walidują dane oraz mają ograniczenia adekwatne do ryzyka nadużycia." },
      { title: "Lepsza aktualizowalność", description: "Zależności i konfiguracja mają określony proces przeglądu zamiast pozostawać bez właściciela." },
    ],
    deliverables: [
      { index: "01", title: "Attack surface review", description: "Publiczne endpointy, dane, integracje, sekrety i role.", tags: ["Surface", "Data", "Secrets", "Roles"] },
      { index: "02", title: "Application checks", description: "Walidacja, auth, nagłówki, rate limits i błędy w zależności od stacku.", tags: ["Validation", "Auth", "Headers", "Limits"] },
      { index: "03", title: "Dependency + deploy review", description: "Zależności, build, sekrety CI i konfiguracja środowiska.", tags: ["Dependencies", "CI", "Deploy", "Secrets"] },
      { index: "04", title: "Remediation plan", description: "Priorytety poprawek według wpływu i wykonalności.", tags: ["Risk", "Priority", "Fix", "QA"] },
    ],
    process: [
      { title: "Model", description: "Ustalamy dane, role i publiczną powierzchnię." },
      { title: "Review", description: "Sprawdzamy kod i konfigurację w określonym zakresie." },
      { title: "Remediate", description: "Wdrażamy lub dokumentujemy poprawki według ryzyka." },
      { title: "Verify", description: "Powtarzamy krytyczne testy po zmianach." },
    ],
    faqs: [
      { question: "Czy możecie zagwarantować, że strona nigdy nie zostanie zaatakowana?", answer: "Nie. Bezpieczeństwo to zarządzanie ryzykiem i redukcja powierzchni ataku, nie absolutna gwarancja." },
      { question: "Czy strona statyczna też wymaga bezpieczeństwa?", answer: "Tak, choć ma zwykle mniejszą powierzchnię serwerową. Nadal znaczenie mają zależności, deploy, DNS, domena, skrypty zewnętrzne i konto repozytorium." },
      { question: "Czy audyt bezpieczeństwa zastępuje pentest?", answer: "Nie. Zakres przeglądu aplikacyjnego może być inny niż formalny test penetracyjny prowadzony według odrębnej metodologii." },
    ],
    related: ["audyt-strony", "uslugi/hosting-deploy", "uslugi/utrzymanie-stron"],
  },
  "hosting-deploy": {
    key: "hosting-deploy",
    slug: "uslugi/hosting-deploy",
    label: "Hosting i deployment",
    pillar: "CARE",
    code: "CARE / DEPLOY",
    eyebrow: "LEADFLOWAI / HOSTING + DEPLOYMENT",
    title: "Hosting i deployment dobrane do architektury strony.",
    lead: "Konfigurujemy build, środowiska, domenę, HTTPS, cache i proces wdrożenia tak, aby publikacja była powtarzalna i możliwa do odtworzenia.",
    summary: "Powtarzalny pipeline publikacji, domena, HTTPS, cache i recovery bez ręcznego kopiowania plików na produkcję.",
    directAnswer: "Deployment powinien być procesem, nie jednorazowym kliknięciem. Ustalamy źródło kodu, build, środowiska, konfigurację DNS, HTTPS, cache, sekrety i sposób rollbacku. Hosting dobieramy do tego, czy projekt jest statyczny, serwerowy, korzysta z edge, bazy danych lub zewnętrznych usług.",
    capabilities: ["CI/CD", "GitHub Pages", "Cloudflare", "DNS", "HTTPS", "Caching", "Environments", "Rollback"],
    outcomes: [
      { title: "Powtarzalny deploy", description: "Ta sama wersja kodu przechodzi przez ten sam build i kontrolowane kroki publikacji." },
      { title: "Mniej ręcznych błędów", description: "Artefakt i domena nie zależą od ręcznego kopiowania plików na serwer." },
      { title: "Recovery", description: "Istnieje wiadomość, która wersja działa i jak wrócić do poprzedniego stanu w razie problemu." },
    ],
    deliverables: [
      { index: "01", title: "Hosting architecture", description: "Dobór platformy do statycznego, dynamicznego lub hybrydowego charakteru projektu.", tags: ["Hosting", "Edge", "Server", "Static"] },
      { index: "02", title: "CI/CD", description: "Build, testy, artefakt i publikacja z repozytorium.", tags: ["CI", "Build", "Artifact", "Deploy"] },
      { index: "03", title: "Domain + HTTPS", description: "DNS, custom domain, certyfikat i wymagane przekierowania.", tags: ["DNS", "Domain", "TLS", "Redirects"] },
      { index: "04", title: "Recovery plan", description: "Wersjonowanie, rollback i podstawowa procedura awaryjna.", tags: ["Rollback", "Recovery", "Version", "Runbook"] },
    ],
    process: [
      { title: "Requirements", description: "Ustalamy runtime, ruch, dane i ograniczenia platformy." },
      { title: "Pipeline", description: "Budujemy ścieżkę repo → test → artifact → deploy." },
      { title: "Domain", description: "Konfigurujemy DNS, HTTPS i cache." },
      { title: "Recovery test", description: "Sprawdzamy identyfikację wersji i procedurę cofnięcia." },
    ],
    faqs: [
      { question: "Czy każda strona potrzebuje VPS?", answer: "Nie. Statyczny serwis często lepiej działa na prostym hostingu CDN/Pages bez utrzymywania własnego serwera." },
      { question: "Czy Cloudflare musi proxyować stronę?", answer: "Nie. Tryb zależy od architektury DNS, hostingu i funkcji, których faktycznie potrzebujemy." },
      { question: "Czy deployment może być automatyczny?", answer: "Tak, ale produkcyjna publikacja powinna mieć odpowiednie testy i zasady autoryzacji dla ryzyka projektu." },
    ],
    related: ["uslugi/core-web-vitals", "uslugi/bezpieczenstwo-stron", "uslugi/utrzymanie-stron"],
  },
  "utrzymanie-stron": {
    key: "utrzymanie-stron",
    slug: "uslugi/utrzymanie-stron",
    label: "Utrzymanie i rozwój",
    pillar: "CARE",
    code: "CARE / MAINTENANCE",
    eyebrow: "LEADFLOWAI / UTRZYMANIE STRON",
    title: "Utrzymanie strony jako kontrolowany proces zmian, monitoringu i rozwoju.",
    lead: "Obsługujemy poprawki, aktualizacje, obserwację błędów, regresję i rozwój treści lub funkcji w modelu dopasowanym do krytyczności serwisu.",
    summary: "Monitoring, aktualizacje, regresja i rozwój po publikacji zamiast porzucenia projektu w dniu launchu.",
    directAnswer: "Po publikacji strona nadal zmienia się wraz z ofertą, zależnościami, wyszukiwarkami i integracjami. Utrzymanie obejmuje kontrolę zmian, aktualizacje, diagnostykę awarii i okresową walidację krytycznych funkcji. Zakres SLA lub dyżuru ustalamy osobno, jeśli projekt rzeczywiście tego wymaga.",
    capabilities: ["Monitoring", "Updates", "Bugfix", "Regression", "Content", "Security", "Performance", "Roadmap"],
    outcomes: [
      { title: "Mniej niekontrolowanych zmian", description: "Aktualizacje przechodzą przez ustalony proces zamiast bezpośredniej edycji produkcji." },
      { title: "Szybsza diagnoza", description: "Znane źródło kodu, logi i runbook ułatwiają ustalenie przyczyny problemu." },
      { title: "Ciągły rozwój", description: "Nowe treści i funkcje mogą być planowane na podstawie priorytetów oraz danych." },
    ],
    deliverables: [
      { index: "01", title: "Maintenance scope", description: "Zakres systemów, odpowiedzialności i typy zmian objęte opieką.", tags: ["Scope", "Ownership", "Priority", "SLA"] },
      { index: "02", title: "Monitoring + checks", description: "Kontrole dostępności, błędów i krytycznych ścieżek zależnie od architektury.", tags: ["Uptime", "Errors", "Smoke", "Alerts"] },
      { index: "03", title: "Update process", description: "Zależności, poprawki, testy i sposób publikowania zmian.", tags: ["Updates", "CI", "QA", "Deploy"] },
      { index: "04", title: "Roadmap", description: "Lista rozwoju wynikająca z problemów, danych i celów biznesowych.", tags: ["Roadmap", "CRO", "SEO", "Product"] },
    ],
    process: [
      { title: "Handover", description: "Ustalamy stan, architekturę, dostępy i odpowiedzialności." },
      { title: "Observe", description: "Włączamy właściwe kontrole i priorytety błędów." },
      { title: "Maintain", description: "Realizujemy poprawki oraz aktualizacje przez kontrolowany workflow." },
      { title: "Improve", description: "Plan rozwoju opieramy na potrzebach i danych zamiast przypadkowych dodatkach." },
    ],
    faqs: [
      { question: "Czy utrzymanie jest obowiązkowe po każdym projekcie?", answer: "Nie. Zakres zależy od technologii, krytyczności i tego, kto przejmuje odpowiedzialność po wdrożeniu." },
      { question: "Czy opieka obejmuje rozwój SEO i treści?", answer: "Może obejmować, jeśli zostanie to włączone do zakresu. Utrzymanie techniczne i rozwój widoczności są rozdzielnymi odpowiedzialnościami." },
      { question: "Czy możecie przejąć istniejącą stronę?", answer: "Tak po audycie stanu, repozytorium, hostingu, zależności i dostępu do niezbędnych systemów." },
    ],
    related: ["uslugi/hosting-deploy", "uslugi/core-web-vitals", "modernizacja-stron"],
  },
} as const satisfies Record<string, ExtendedServicePage>;

export type ExtendedServiceKey = keyof typeof extendedServicePages;

export function getExtendedServicePage(key: string): ExtendedServicePage | undefined {
  return extendedServicePages[key as ExtendedServiceKey];
}

export function getExtendedServiceByPath(path: string): ExtendedServicePage | undefined {
  return Object.values(extendedServicePages).find((page) => page.slug === path);
}

export function getExtendedServiceMetadata(key: string): Metadata {
  const page = getExtendedServicePage(key);
  if (!page) return {};
  return {
    title: page.title,
    description: page.lead,
    alternates: { canonical: `/${page.slug}` },
    openGraph: {
      type: "website",
      locale: "pl_PL",
      url: `${site.url}/${page.slug}`,
      siteName: site.name,
      title: page.title,
      description: page.lead,
    },
  };
}

export const extendedServiceLinks = Object.values(extendedServicePages).map((page) => ({
  slug: page.slug,
  label: page.label,
  pillar: page.pillar,
  summary: page.summary,
})) as readonly {
  slug: string;
  label: string;
  pillar: ServicePillar;
  summary: string;
}[];
