import type { KnowledgeArticle } from "@/lib/knowledge";

export type KnowledgeSource = { label: string; href: string };
export type SourcedKnowledgeArticle = KnowledgeArticle & { sources?: readonly KnowledgeSource[] };

export const expandedKnowledgeArticles = [
  {
    slug: "ile-kosztuje-profesjonalna-strona-internetowa",
    eyebrow: "WWW / BUDŻET",
    title: "Ile kosztuje profesjonalna strona internetowa i od czego naprawdę zależy wycena?",
    description: "Co buduje koszt strony: zakres informacji, design, development, CMS, integracje, SEO/AEO/GEO, QA, utrzymanie i ryzyko projektu.",
    summary: "Cena strony nie wynika wyłącznie z liczby podstron. Największe różnice tworzą poziom indywidualnego projektu, złożoność funkcji, jakość treści, integracje, wymagania wydajnościowe, proces QA i odpowiedzialność po publikacji.",
    sections: [
      { title: "1. Zacznij od pracy, którą strona ma wykonywać", paragraphs: ["Strona-wizytówka, serwis usługowy, landing kampanii, sklep i aplikacja webowa rozwiązują inne problemy. Próba porównywania ich tylko liczbą ekranów prowadzi do błędnej wyceny.", "Pierwszym krokiem jest określenie celu, odbiorców, informacji potrzebnej do decyzji i funkcji, które muszą działać po publikacji."] },
      { title: "2. Najwięcej kosztują decyzje i zależności, nie sam HTML", paragraphs: ["Indywidualna architektura informacji, UX/UI, treść, system komponentów, integracje z zewnętrznymi usługami i migracja danych wymagają analizy oraz testów. Gotowy szablon może skrócić część pracy, ale nie usuwa potrzeb biznesowych."] },
      { title: "3. Wycena powinna oddzielać fundament od modułów", paragraphs: ["Dobrym modelem jest rozdzielenie rdzenia — architektury, designu, developmentu, responsive i QA — od modułów takich jak CMS, e-commerce, AI, automatyzacje, analityka czy stała opieka.", "Dzięki temu wiadomo, które elementy są konieczne na start, a które można dołożyć później bez przebudowy wszystkiego."] },
      { title: "4. Najtańsza realizacja może być najdroższa w utrzymaniu", paragraphs: ["Jeżeli projekt nie ma źródła prawdy, wersjonowania, dokumentacji i testów, każda późniejsza zmiana może wymagać ponownego odkrywania architektury. Koszt całkowity obejmuje także utrzymanie, poprawki i ryzyko migracji."] },
    ],
    related: [{ href: "/uslugi", label: "Pełna oferta" }, { href: "/strony-internetowe", label: "Strony internetowe" }, { href: "/kontakt", label: "Opisz projekt do wyceny" }],
  },
  {
    slug: "jak-wybrac-technologie-do-strony-internetowej",
    eyebrow: "WWW / TECHNOLOGIA",
    title: "Jak wybrać technologię do strony internetowej bez kupowania problemu na kilka lat?",
    description: "Kiedy wystarczy statyczna strona, kiedy CMS, headless, Next.js, e-commerce albo aplikacja webowa i jakie pytania zadać przed wyborem.",
    summary: "Technologia powinna wynikać z modelu publikacji, funkcji, integracji, wydajności, kompetencji zespołu i sposobu utrzymania. Popularność frameworka nie jest wystarczającym kryterium.",
    sections: [
      { title: "1. Najpierw model treści i funkcji", paragraphs: ["Jeżeli treść zmienia się kilka razy w roku, pełny CMS może być zbędny. Jeżeli wielu redaktorów codziennie publikuje materiały, ręczna edycja repozytorium będzie niewygodna.", "Tak samo z backendem: nie warto utrzymywać serwera tylko dlatego, że framework go obsługuje, jeśli serwis może być statyczny."] },
      { title: "2. Policz integracje i odpowiedzialność operacyjną", paragraphs: ["Płatności, CRM, logowanie, panel użytkownika, dane na żywo i automatyzacje zmieniają architekturę bardziej niż sam wygląd. Każda integracja ma limity, sekrety, tryby awarii i koszty utrzymania."] },
      { title: "3. Oceń możliwość rozwoju", paragraphs: ["Technologia nie musi obsługiwać wszystkich hipotetycznych funkcji przyszłości. Powinna natomiast pozwalać rozsądnie dodać najbardziej prawdopodobne moduły bez łamania istniejącego produktu."] },
      { title: "4. Wybierz system, który da się przekazać", paragraphs: ["Dokumentacja, standardowy stack, kontrola wersji i jasny proces deploymentu zmniejszają zależność od jednej osoby. To często ważniejsze niż marginalna przewaga benchmarkowa konkretnej biblioteki."] },
    ],
    related: [{ href: "/web-development", label: "Web development" }, { href: "/cms-headless", label: "CMS i headless" }, { href: "/aplikacje-webowe", label: "Aplikacje webowe" }],
  },
  {
    slug: "core-web-vitals-lcp-inp-cls-praktycznie",
    eyebrow: "PERFORMANCE / CWV",
    title: "Core Web Vitals: jak praktycznie diagnozować LCP, INP i CLS bez polowania na wynik 100?",
    description: "Praktyczne podejście do LCP, INP i CLS: field data, profiling, obrazy, JavaScript, layout, third-party i budżety regresji.",
    summary: "Core Web Vitals pomagają opisać ładowanie, responsywność i stabilność interfejsu, ale wynik laboratoryjny nie powinien zastępować diagnozy. Najpierw trzeba znaleźć element lub pracę powodującą koszt, a dopiero potem optymalizować.",
    sections: [
      { title: "1. LCP: znajdź największy element, a nie magiczną regułę", paragraphs: ["Largest Contentful Paint zależy od czasu odpowiedzi, priorytetu zasobu, renderowania i tego, co faktycznie jest największym elementem w viewport. Hero image, font albo blok tekstu wymagają innych napraw."] },
      { title: "2. INP: szukaj długiej pracy na głównym wątku", paragraphs: ["Interaction to Next Paint dotyczy responsywności po interakcji. Ciężki JavaScript, duże renderowanie komponentów lub synchroniczne operacje mogą blokować reakcję niezależnie od szybkości pierwszego ładowania."] },
      { title: "3. CLS: rezerwuj przestrzeń i kontroluj późne zmiany", paragraphs: ["Obrazy bez wymiarów, fonty, reklamy, bannery i dynamiczne moduły mogą przesuwać treść po rozpoczęciu czytania. Rozwiązaniem jest projektowanie stabilnego miejsca, nie ukrywanie przesunięć animacją."] },
      { title: "4. Po naprawie ustaw budżet regresji", paragraphs: ["Jeżeli strona ma zaakceptowany ciężar JavaScript, CSS i obrazów, warto pilnować go w CI. Budżet nie gwarantuje dobrych CWV, ale chroni przed przypadkowym powrotem części problemów."] },
    ],
    related: [{ href: "/core-web-vitals", label: "Optymalizacja Core Web Vitals" }, { href: "/audyt-strony", label: "Audyt strony" }, { href: "/strony-internetowe", label: "Budowa strony" }],
    sources: [{ label: "web.dev — Web Vitals", href: "https://web.dev/articles/vitals" }, { label: "web.dev — progi Core Web Vitals", href: "https://web.dev/articles/defining-core-web-vitals-thresholds" }],
  },
  {
    slug: "wcag-22-co-sprawdzic-na-stronie",
    eyebrow: "ACCESSIBILITY / WCAG",
    title: "WCAG 2.2 na stronie internetowej: co trzeba sprawdzić poza kontrastem kolorów?",
    description: "Semantyka, klawiatura, focus, formularze, alternatywy tekstowe, motion i ręczne testy dostępności zgodne z podejściem WCAG 2.2.",
    summary: "Dostępność nie sprowadza się do kontrastu i automatycznego skanera. Trzeba ocenić strukturę, obsługę klawiaturą, widoczność focusu, etykiety, komunikaty błędów, media, ruch oraz pełne wykonanie kluczowych zadań.",
    sections: [
      { title: "1. Semantyka opisuje strukturę", paragraphs: ["Nagłówki, landmarki, listy, przyciski i formularze powinny używać elementów odpowiadających ich funkcji. Poprawna semantyka pomaga technologii wspomagającej zrozumieć stronę bez zgadywania z wyglądu."] },
      { title: "2. Klawiatura i focus muszą pozwalać wykonać zadanie", paragraphs: ["Użytkownik powinien móc przejść przez interaktywne elementy w logicznej kolejności, widzieć aktualny focus i nie zostać uwięziony w komponencie takim jak modal czy menu."] },
      { title: "3. Formularz potrzebuje etykiet i zrozumiałych błędów", paragraphs: ["Placeholder nie jest pełnym zamiennikiem etykiety. Błąd powinien wskazywać problem i sposób poprawy, a ważna informacja nie może być komunikowana wyłącznie kolorem."] },
      { title: "4. Automat jest pomocą, nie certyfikatem", paragraphs: ["Skaner wykrywa część problemów kodu, ale nie oceni wszystkich aspektów sensu, kolejności, zrozumiałości czy działania kluczowego procesu. Audyt wymaga również testów ręcznych."] },
    ],
    related: [{ href: "/dostepnosc-wcag", label: "Dostępność WCAG" }, { href: "/ux-ui-design", label: "UX/UI design" }, { href: "/audyt-strony", label: "Audyt strony" }],
    sources: [{ label: "W3C — WCAG 2.2", href: "https://www.w3.org/TR/WCAG22/" }, { label: "W3C WAI — WCAG 2 w skrócie", href: "https://www.w3.org/WAI/standards-guidelines/wcag/glance/pl" }],
  },
  {
    slug: "cro-jak-znalezc-problemy-z-konwersja",
    eyebrow: "CONVERSION / CRO",
    title: "CRO bez zgadywania: jak znaleźć realne problemy z konwersją na stronie?",
    description: "Mapa konwersji, tarcie, analityka, formularze, dowody i hipotezy — praktyczny model audytu CRO przed zmianami interfejsu.",
    summary: "Optymalizacja konwersji zaczyna się od zdefiniowania wartościowego działania i zrozumienia, dlaczego użytkownik go nie wykonuje. Dopiero potem ma sens zmiana komunikatu, układu, CTA lub formularza.",
    sections: [
      { title: "1. Zdefiniuj konwersję i mikro-konwersje", paragraphs: ["Kontakt, zakup czy rezerwacja mogą być celem głównym, ale wcześniej użytkownik porównuje ofertę, czyta dowód, otwiera cennik lub rozpoczyna formularz. Te kroki pomagają zlokalizować problem."] },
      { title: "2. Oddziel brak ruchu od słabej konwersji", paragraphs: ["Strona może mieć mało zapytań dlatego, że prawie nikt na nią nie trafia. CRO nie zastąpi pozyskania odpowiedniego ruchu, tak jak SEO nie naprawi źle zaprojektowanego procesu kontaktu."] },
      { title: "3. Szukaj tarcia informacyjnego i technicznego", paragraphs: ["Niejasna oferta, brak odpowiedzi na obiekcję, trudny formularz, słaby mobile lub błąd integracji mogą wyglądać w danych podobnie. Dlatego analiza powinna łączyć zachowanie użytkowników z ręcznym przejściem ścieżki."] },
      { title: "4. Wdrażaj hipotezy, nie dekoracje", paragraphs: ["Każda ważna zmiana powinna mieć opis problemu, przewidywany wpływ i sposób oceny. Bez tego po redesignie wiadomo tylko, że strona jest inna."] },
    ],
    related: [{ href: "/cro-optymalizacja-konwersji", label: "Optymalizacja CRO" }, { href: "/analityka-webowa", label: "Analityka webowa" }, { href: "/formularze-lead-generation", label: "Formularze i lead generation" }],
  },
  {
    slug: "plan-pomiaru-analityka-strony",
    eyebrow: "ANALYTICS / MEASUREMENT",
    title: "Plan pomiaru strony: jakie zdarzenia mierzyć, żeby analityka pomagała podejmować decyzje?",
    description: "Jak zbudować measurement plan: cele, KPI, mikro-konwersje, event taxonomy, parametry, walidacja i prywatność.",
    summary: "Najpierw trzeba określić pytania biznesowe, a dopiero potem implementować zdarzenia. Pomiar wszystkiego prowadzi do większej liczby danych, ale niekoniecznie do lepszych decyzji.",
    sections: [
      { title: "1. Zacznij od decyzji, nie od narzędzia", paragraphs: ["Jeżeli chcesz ocenić jakość leadów, potrzebujesz innych danych niż przy optymalizacji checkoutu. Narzędzie analityczne powinno realizować plan pomiaru, nie dyktować model strony."] },
      { title: "2. Zbuduj spójną taksonomię zdarzeń", paragraphs: ["Nazwy i parametry powinny opisywać znaczenie biznesowe. Zdarzenie `form_submit` jest bardziej użyteczne, gdy wiadomo jaki formularz, z jakiej strony i czy wysłanie zakończyło się powodzeniem."] },
      { title: "3. Rozróżnij intencję od sukcesu technicznego", paragraphs: ["Kliknięcie w przycisk wysyłania nie jest jeszcze poprawnie dostarczonym leadem. Dla krytycznych konwersji warto mierzyć stan potwierdzony przez system, jeśli architektura pozwala to zrobić wiarygodnie."] },
      { title: "4. Zbieraj tylko dane potrzebne", paragraphs: ["Większa ilość danych zwiększa koszt analizy i ryzyko prywatności. Minimalizacja danych jest dobrym domyślnym założeniem również z punktu widzenia jakości modelu analitycznego."] },
    ],
    related: [{ href: "/analityka-webowa", label: "Analityka webowa" }, { href: "/cro-optymalizacja-konwersji", label: "CRO" }, { href: "/formularze-lead-generation", label: "Lead generation" }],
  },
  {
    slug: "landing-page-jak-zaprojektowac",
    eyebrow: "CONVERSION / LANDING",
    title: "Jak zaprojektować landing page, który prowadzi do jednego celu bez utraty ważnych informacji?",
    description: "Intencja, oferta, dowody, CTA, formularz, szybkość i pomiar — architektura skutecznego landing page bez uniwersalnych szablonów.",
    summary: "Landing page powinien ograniczać konkurencyjne ścieżki, ale nie może usuwać informacji potrzebnych do decyzji. Kluczowa jest zgodność źródła ruchu, komunikatu strony i działania końcowego.",
    sections: [
      { title: "1. Dopasuj stronę do źródła ruchu", paragraphs: ["Użytkownik z reklamy konkretnej usługi ma inną intencję niż osoba wchodząca z ogólnej frazy organicznej. Nagłówek i pierwsza odpowiedź powinny potwierdzać, że trafił we właściwe miejsce."] },
      { title: "2. Jedno główne CTA nie oznacza jednej informacji", paragraphs: ["Użytkownik nadal może potrzebować zakresu, procesu, FAQ, dowodów i informacji o ryzyku. Ograniczamy konkurencyjne akcje, nie kontekst potrzebny do zaufania."] },
      { title: "3. Formularz powinien odpowiadać wartości następnego kroku", paragraphs: ["Im większe zobowiązanie, tym więcej kontekstu może być uzasadnione. Krótki formularz nie jest automatycznie lepszy, jeśli generuje zapytania, których nie da się obsłużyć."] },
      { title: "4. Mierz cały funnel", paragraphs: ["Warto wiedzieć nie tylko ile osób wysłało formularz, ale również ilu użytkowników rozpoczęło go, otworzyło kluczowe sekcje lub przerwało na konkretnym etapie."] },
    ],
    related: [{ href: "/landing-pages", label: "Landing pages" }, { href: "/cro-optymalizacja-konwersji", label: "CRO" }, { href: "/analityka-webowa", label: "Analityka" }],
  },
  {
    slug: "architektura-sklepu-internetowego-seo-cro",
    eyebrow: "E-COMMERCE / ARCHITECTURE",
    title: "Architektura sklepu internetowego: jak połączyć katalog, SEO i drogę do zakupu?",
    description: "Kategorie, filtry, strony produktów, warianty, checkout, dane produktowe, schema i pomiar jako jeden system e-commerce.",
    summary: "Sklep musi jednocześnie odpowiadać sposobowi wyszukiwania produktów, ułatwiać porównanie i prowadzić do bezpiecznego zakupu. Architektura katalogu wpływa więc na UX, SEO, dane i operacje.",
    sections: [
      { title: "1. Kategorie powinny odpowiadać sposobowi wyboru", paragraphs: ["Drzewo kategorii nie musi kopiować struktury magazynowej. Powinno pomagać użytkownikowi zawężać ofertę według cech istotnych dla decyzji."] },
      { title: "2. Filtry mogą tworzyć problem indeksacji", paragraphs: ["Każda kombinacja parametrów nie powinna automatycznie stawać się stroną indeksowalną. Trzeba rozdzielić użyteczność filtrowania od architektury URL i powierzchni crawl."] },
      { title: "3. Strona produktu potrzebuje kompletnego modelu danych", paragraphs: ["Cena, dostępność, wariant, zdjęcia, parametry i identyfikatory powinny pochodzić z kontrolowanego źródła, szczególnie gdy dane są wysyłane dalej do integracji lub structured data."] },
      { title: "4. Checkout jest procesem krytycznym", paragraphs: ["Błędy płatności, utrata koszyka, niejasne koszty dostawy i formularze adresowe wymagają osobnego QA. Estetyka karty produktu nie rekompensuje niedziałającego procesu zakupu."] },
    ],
    related: [{ href: "/sklepy-internetowe", label: "Sklepy internetowe" }, { href: "/seo", label: "SEO" }, { href: "/cro-optymalizacja-konwersji", label: "CRO" }],
  },
  {
    slug: "rag-na-stronie-jak-zaprojektowac",
    eyebrow: "AI / RAG",
    title: "RAG na stronie: jak zaprojektować bazę wiedzy i fallback, żeby chatbot nie udawał źródła prawdy?",
    description: "Źródła, chunking, retrieval, cytowanie, guardrails, testy i fallback w systemach RAG dla stron i aplikacji.",
    summary: "Retrieval-Augmented Generation może dostarczyć modelowi kontekst z zatwierdzonych materiałów, ale nie gwarantuje poprawnej odpowiedzi. Potrzebna jest kontrola źródeł, retrieval, instrukcji i sytuacji, w których system powinien odmówić.",
    sections: [
      { title: "1. Najpierw zdefiniuj publiczne źródło prawdy", paragraphs: ["Dokumenty, strony i dane używane przez RAG powinny być zatwierdzone i mieć właściciela. Jeżeli źródła są sprzeczne, retrieval tylko szybciej dostarczy modelowi sprzeczność."] },
      { title: "2. Chunking powinien zachowywać kontekst", paragraphs: ["Dzielenie dokumentu na arbitralne kawałki może odciąć warunki od odpowiedzi. Segmentacja powinna odpowiadać strukturze informacji i zachowywać informacje potrzebne do prawidłowej interpretacji."] },
      { title: "3. Retrieval trzeba testować oddzielnie od generacji", paragraphs: ["Jeżeli właściwy fragment nie trafia do kontekstu, zmiana promptu nie naprawi problemu. Warto mierzyć trafność wyszukiwania i jakość odpowiedzi jako osobne etapy."] },
      { title: "4. Fallback jest częścią produktu", paragraphs: ["Gdy źródło nie zawiera odpowiedzi, bezpieczniejszym zachowaniem może być jawne `nie wiem`, wskazanie materiału lub przekazanie do człowieka zamiast generowania wiarygodnie brzmiącej odpowiedzi."] },
    ],
    related: [{ href: "/chatboty-ai", label: "Chatboty AI" }, { href: "/integracje-ai", label: "Integracje AI" }, { href: "/wiedza/chatbot-na-stronie-kiedy-ma-sens", label: "Kiedy chatbot ma sens" }],
  },
  {
    slug: "integracja-api-checklista-produkcyjna",
    eyebrow: "INTEGRATION / API",
    title: "Integracja API na produkcji: checklista timeoutów, retry, idempotencji i obsługi błędów.",
    description: "Co trzeba zaprojektować poza happy path: auth, timeout, retry, idempotencja, rate limits, walidacja, logi i ręczny fallback.",
    summary: "Połączenie działa nie wtedy, gdy jeden request zwróci 200, lecz wtedy, gdy system ma przewidywalne zachowanie również przy duplikacie, timeout, limicie i częściowej awarii dostawcy.",
    sections: [
      { title: "1. Ustal source of truth", paragraphs: ["Jeżeli dwa systemy mogą edytować ten sam stan, trzeba ustalić priorytet i sposób rozwiązywania konfliktów. Bez tego synchronizacja tworzy trudne do odtworzenia błędy biznesowe."] },
      { title: "2. Timeout i retry muszą być celowe", paragraphs: ["Automatyczne ponawianie operacji zapisu bez idempotencji może utworzyć duplikaty. Retry powinien zależeć od typu błędu i charakteru operacji."] },
      { title: "3. Waliduj odpowiedź, nie tylko status", paragraphs: ["HTTP 200 nie gwarantuje, że dane mają oczekiwaną strukturę lub znaczenie. Kontrakt integracji powinien definiować wymagane pola i obsługę zmian schematu."] },
      { title: "4. Zaprojektuj obserwowalność i ręczny fallback", paragraphs: ["Dla istotnego procesu trzeba móc ustalić, która operacja nie przeszła, z jakiego powodu i jak bezpiecznie ją powtórzyć lub dokończyć ręcznie."] },
    ],
    related: [{ href: "/integracje-api", label: "Integracje API" }, { href: "/automatyzacje-www", label: "Automatyzacje WWW" }, { href: "/bezpieczenstwo-stron", label: "Bezpieczeństwo WWW" }],
  },
  {
    slug: "bezpieczenstwo-strony-powierzchnia-ataku",
    eyebrow: "SECURITY / WEB",
    title: "Bezpieczeństwo strony: jak rozpoznać realną powierzchnię ataku przed dokładaniem zabezpieczeń?",
    description: "Sekrety, endpointy, formularze, third-party scripts, auth, dependencies i recovery — model bezpieczeństwa zależny od architektury.",
    summary: "Najpierw trzeba wiedzieć, gdzie strona przyjmuje dane, przechowuje sekrety i wykonuje operacje. Statyczna witryna i aplikacja z kontami użytkowników mają zupełnie inną powierzchnię ataku.",
    sections: [
      { title: "1. Zinwentaryzuj punkty zapisu i dane", paragraphs: ["Formularz, webhook, panel, płatność i upload pliku są ważniejsze z punktu widzenia zagrożeń niż czysto prezentacyjny komponent. Każdy punkt wejścia powinien mieć określony poziom zaufania."] },
      { title: "2. Sekret nie może zależeć od dyskrecji frontendu", paragraphs: ["Kod przeglądarki jest dostępny użytkownikowi. Klucze dające uprzywilejowany dostęp powinny pozostać w kontrolowanej warstwie serwerowej lub odpowiednim magazynie sekretów."] },
      { title: "3. Zależności są częścią produktu", paragraphs: ["Biblioteki, pluginy i usługi zewnętrzne mają własny cykl aktualizacji. Im więcej zależności, tym większa odpowiedzialność za monitoring zmian i podatności."] },
      { title: "4. Recovery jest częścią security", paragraphs: ["Backup, rollback i możliwość odtworzenia konfiguracji skracają czas skutków błędu lub incydentu. Sama prewencja nie wystarcza."] },
    ],
    related: [{ href: "/bezpieczenstwo-stron", label: "Bezpieczeństwo WWW" }, { href: "/hosting-deploy", label: "Hosting i deployment" }, { href: "/opieka-utrzymanie-stron", label: "Opieka i utrzymanie" }],
  },
  {
    slug: "cms-czy-headless-cms",
    eyebrow: "CONTENT / CMS",
    title: "CMS czy headless CMS: jak dobrać model edycji treści do realnej pracy zespołu?",
    description: "Kiedy klasyczny CMS, headless albo brak CMS ma sens: redaktorzy, modele treści, preview, integracje, wydajność i utrzymanie.",
    summary: "Headless nie jest automatycznie nowocześniejszym wyborem. Najpierw trzeba ustalić kto publikuje, jak często, ile typów treści istnieje i czy te same dane mają trafiać do wielu kanałów.",
    sections: [
      { title: "1. Zacznij od redaktora", paragraphs: ["Panel powinien odzwierciedlać realne zadania osoby publikującej. Jeśli każda zmiana wymaga znajomości struktury komponentów, CMS nie spełnia swojej podstawowej roli."] },
      { title: "2. Model treści jest ważniejszy od edytora WYSIWYG", paragraphs: ["Usługa, artykuł, osoba czy lokalizacja mają własne pola i relacje. Strukturalne dane ułatwiają spójność, linkowanie i ponowne użycie informacji."] },
      { title: "3. Headless dodaje elastyczność i zależności", paragraphs: ["Oddzielenie backendu treści od frontendu ułatwia własny interfejs i wiele kanałów, ale wymaga integracji API, preview, deploymentu i obsługi dwóch systemów."] },
      { title: "4. Czasem najlepszym CMS jest brak CMS", paragraphs: ["Mały serwis aktualizowany kilka razy w roku może być prostszy jako statyczny projekt z kontrolą wersji. Nie warto utrzymywać panelu, którego nikt regularnie nie używa."] },
    ],
    related: [{ href: "/cms-headless", label: "CMS i headless" }, { href: "/copywriting-content", label: "Treść i copywriting" }, { href: "/strony-internetowe", label: "Strony internetowe" }],
  },
  {
    slug: "strona-wielojezyczna-hreflang-seo",
    eyebrow: "SEARCH / I18N",
    title: "Strona wielojęzyczna a SEO: routing, hreflang, canonical i workflow tłumaczeń.",
    description: "Jak projektować wersje językowe bez chaosu URL: locale, odpowiedniki stron, hreflang, canonical, sitemap i kontrola tłumaczeń.",
    summary: "Wersje językowe powinny mieć jednoznaczne adresy i relacje między odpowiednikami. Największym problemem nie jest sam przełącznik języka, lecz utrzymanie spójnej treści, metadata i sygnałów wyszukiwarki.",
    sections: [
      { title: "1. Wybierz stabilny model URL", paragraphs: ["Katalogi, subdomeny i osobne domeny mogą działać, ale migracje między modelami są kosztowne. Ważne jest konsekwentne mapowanie locale na publiczny adres."] },
      { title: "2. hreflang łączy odpowiedniki, nie dowolne strony", paragraphs: ["Relacje powinny wskazywać faktyczne odpowiedniki językowe. Jeżeli dana treść nie istnieje w drugim języku, lepiej nie tworzyć sztucznego połączenia tylko po to, aby komplet wyglądał estetycznie."] },
      { title: "3. Canonical nie powinien kasować wersji językowej", paragraphs: ["Prawidłowo przygotowane wersje lokalizowane są osobnymi stronami. Canonical i hreflang rozwiązują inne problemy i muszą odzwierciedlać rzeczywistą architekturę."] },
      { title: "4. Tłumaczenie wymaga procesu aktualizacji", paragraphs: ["Jeżeli polska oferta zmieni się dziś, trzeba wiedzieć kiedy i przez kogo zostaną zaktualizowane pozostałe języki. Inaczej serwis szybko zaczyna publikować sprzeczne informacje."] },
    ],
    related: [{ href: "/strony-wielojezyczne", label: "Strony wielojęzyczne" }, { href: "/seo", label: "SEO" }, { href: "/cms-headless", label: "CMS i headless" }],
  },
  {
    slug: "ai-search-google-co-robic-2026",
    eyebrow: "AI SEARCH / 2026",
    title: "Widoczność w generatywnej AI Google w 2026: co robić na stronie, a czego nie wymyślać?",
    description: "Aktualne podejście Google do funkcji generatywnej AI: fundamenty SEO, helpful content, crawlability, visible text, structured data i brak specjalnego schema AI.",
    summary: "Google wskazuje, że dla funkcji generatywnej AI nadal obowiązują podstawowe praktyki SEO i tworzenie pomocnych, wiarygodnych treści. Nie ma specjalnego znacznika schema.org wymaganego do AI Search, a structured data powinny odpowiadać widocznej treści.",
    sections: [
      { title: "1. Nie buduj osobnej wersji strony dla AI", paragraphs: ["Najmocniejszym fundamentem jest ta sama publiczna informacja dla użytkownika, crawlera i danych maszynowych. Encje, oferta i dowody nie powinny mieć sprzecznych wersji zależnie od kanału."] },
      { title: "2. Techniczna dostępność nadal jest podstawą", paragraphs: ["Crawler musi móc znaleźć stronę, pobrać istotną treść i zrozumieć relacje wewnętrzne. Robots, canonical, sitemap i internal linking nadal mają znaczenie niezależnie od sposobu prezentacji odpowiedzi użytkownikowi."] },
      { title: "3. Nie istnieje specjalny schema do generatywnej AI", paragraphs: ["Structured data mogą pomagać opisać fakty i typy treści, ale Google wprost ostrzega przed nadmiernym skupieniem na markupie i nie wymaga specjalnego znacznika dla generatywnej AI."] },
      { title: "4. Masowa produkcja podobnych stron jest ryzykiem, nie strategią GEO", paragraphs: ["Tworzenie wielu stron głównie po to, aby przechwytywać podobne zapytania, może wejść w zasady scaled content abuse lub doorway abuse. Dlatego każdy publiczny URL powinien mieć własną rolę i wartość dla użytkownika."] },
    ],
    related: [{ href: "/geo-ai-search", label: "GEO / AI Search" }, { href: "/seo-aeo-geo", label: "SEO + AEO + GEO" }, { href: "/copywriting-content", label: "Architektura treści" }],
    sources: [{ label: "Google Search Central — optymalizacja dla generatywnej AI", href: "https://developers.google.com/search/docs/fundamentals/ai-optimization-guide?hl=pl" }, { label: "Google Search Central — funkcje AI a witryna", href: "https://developers.google.com/search/docs/appearance/ai-features?hl=pl" }, { label: "Google Search Central — zasady dotyczące spamu", href: "https://developers.google.com/search/docs/essentials/spam-policies?hl=pl" }],
  },
  {
    slug: "structured-data-kiedy-schema-ma-sens",
    eyebrow: "SEARCH / STRUCTURED DATA",
    title: "Structured data i schema.org: kiedy pomagają, a kiedy stają się tylko dodatkowym kodem?",
    description: "Jak dobierać structured data do widocznej treści, walidować markup i nie używać schema jako ukrytej warstwy marketingowych claimów.",
    summary: "Dane strukturalne powinny opisywać faktycznie widoczną treść i realne encje. Mogą pomagać systemom zrozumieć stronę i kwalifikować ją do wspieranych funkcji, ale nie zastępują treści ani poprawnej architektury.",
    sections: [
      { title: "1. Markup powinien odpowiadać temu, co widzi użytkownik", paragraphs: ["Jeżeli schema opisuje usługę, FAQ lub organizację, te informacje powinny mieć odpowiednik w publicznej treści. Ukryta warstwa z bogatszymi claimami podważa source of truth."] },
      { title: "2. Używaj typów zgodnych z rzeczywistą encją", paragraphs: ["Nie każdy fragment strony potrzebuje osobnego typu. Lepiej poprawnie opisać WebSite, Organization, Service, Article czy BreadcrumbList niż tworzyć rozbudowany graf bez znaczenia dla treści."] },
      { title: "3. Walidacja techniczna nie gwarantuje wyniku w wyszukiwarce", paragraphs: ["Poprawny JSON-LD oznacza tylko, że markup ma oczekiwaną strukturę. Zewnętrzny system decyduje, czy i jak wykorzysta dane."] },
      { title: "4. Schema jest wsparciem dla informacji, nie strategią samą w sobie", paragraphs: ["Jeżeli strona nie ma jasnej oferty, wiarygodnej treści i poprawnego linkowania, dokładanie kolejnych typów structured data nie rozwiąże problemu informacyjnego."] },
    ],
    related: [{ href: "/seo-aeo-geo", label: "SEO + AEO + GEO" }, { href: "/seo", label: "SEO" }, { href: "/geo-ai-search", label: "GEO / AI Search" }],
    sources: [{ label: "Google Search Central — wprowadzenie do structured data", href: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data" }, { label: "Google Search Central — ogólne wytyczne structured data", href: "https://developers.google.com/search/docs/appearance/structured-data/sd-policies" }],
  },
  {
    slug: "architektura-tresci-klastry-tematyczne",
    eyebrow: "CONTENT / ARCHITECTURE",
    title: "Architektura treści i klastry tematyczne: jak rozwijać Wiedzę bez kanibalizacji i masowych cienkich stron?",
    description: "Pillar pages, osobne intencje, internal linking, content gaps i zasady rozbudowy serwisu bez produkowania podobnych URL-i pod każdą frazę.",
    summary: "Dobry klaster tematyczny nie polega na publikowaniu wielu wariantów tego samego artykułu. Strona główna tematu powinna odpowiadać na szeroką intencję, a materiały wspierające rozwijać odrębne pytania i prowadzić między sobą logicznymi linkami.",
    sections: [
      { title: "1. Jedna strona powinna mieć jedną dominującą rolę", paragraphs: ["Jeżeli dwa URL-e odpowiadają praktycznie na to samo pytanie i prowadzą do tego samego działania, warto rozważyć połączenie treści zamiast rozdzielania jej tylko dla dodatkowej frazy."] },
      { title: "2. Materiał wspierający powinien pogłębiać problem", paragraphs: ["Pillar może wyjaśniać SEO jako system, a osobne materiały rozwijać migracje, Core Web Vitals, structured data czy internal linking. Każdy z nich ma wtedy własne pytanie i własną wartość."] },
      { title: "3. Internal linking powinien wynikać z relacji znaczeniowej", paragraphs: ["Link `dowiedz się więcej` bez kontekstu mówi mniej niż link opisujący konkretną usługę lub materiał. Anchor i położenie linku pomagają użytkownikowi przewidzieć następny krok."] },
      { title: "4. Rozbudowę opieraj na lukach informacyjnych", paragraphs: ["Nowy artykuł ma sens, gdy odpowiada na ważne pytanie, którego istniejąca treść nie rozwiązuje wystarczająco dobrze. Sama obecność kolejnej frazy w narzędziu nie jest wystarczającym powodem do nowego URL."] },
    ],
    related: [{ href: "/copywriting-content", label: "Treść i copywriting" }, { href: "/wiedza", label: "Wiedza LeadFlowAI" }, { href: "/seo-aeo-geo", label: "SEO + AEO + GEO" }],
    sources: [{ label: "Google Search Central — helpful, reliable, people-first content", href: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content" }, { label: "Google Search Central — zasady dotyczące spamu", href: "https://developers.google.com/search/docs/essentials/spam-policies?hl=pl" }],
  },
  {
    slug: "automatyzacja-formularz-crm-workflow",
    eyebrow: "AUTOMATION / LEADS",
    title: "Od formularza do CRM: jak zaprojektować automatyzację leada bez gubienia danych i duplikatów?",
    description: "Trigger, walidacja, idempotencja, routing, CRM, alerty i fallback — model niezawodnego workflow po wysłaniu formularza.",
    summary: "Automatyzacja leada powinna rozdzielać przyjęcie danych od kolejnych kroków, posiadać identyfikator operacji i umożliwiać ustalenie, co wydarzyło się przy częściowej awarii integracji.",
    sections: [
      { title: "1. Potwierdź przyjęcie danych przed dalszym łańcuchem", paragraphs: ["Użytkownik nie powinien czekać na pięć zewnętrznych systemów, jeśli można bezpiecznie przyjąć zgłoszenie i przetworzyć kolejne kroki osobno. Model zależy jednak od wymagań biznesowych i infrastruktury."] },
      { title: "2. Nadaj operacji jednoznaczny identyfikator", paragraphs: ["Retry po timeout nie powinien tworzyć dwóch leadów. Idempotencja lub inny mechanizm deduplikacji jest ważny szczególnie przy webhookach i automatycznych powtórzeniach."] },
      { title: "3. Routing powinien być regułą, nie ukrytą logiką", paragraphs: ["Jeśli lead trafia do innego zespołu zależnie od usługi, lokalizacji lub budżetu, reguły powinny być jawne i testowalne."] },
      { title: "4. Fallback musi istnieć zanim pojawi się awaria", paragraphs: ["Gdy CRM jest niedostępny, system powinien wiedzieć czy kolejkuje zapis, wysyła alert, zapisuje dane w bezpiecznym miejscu czy wymaga ręcznego działania."] },
    ],
    related: [{ href: "/automatyzacje-www", label: "Automatyzacje WWW" }, { href: "/formularze-lead-generation", label: "Formularze i leady" }, { href: "/integracje-api", label: "Integracje API" }],
  },
] as const satisfies readonly SourcedKnowledgeArticle[];
