const PUBLIC_LABELS: Record<string, string> = {
  responsive: "Responsywność",
  mobile: "Urządzenia mobilne",
  "mobile-first": "Projektowanie od wersji mobilnej",
  discovery: "Analiza potrzeb",
  content: "Treść",
  "user flow": "Ścieżka użytkownika",
  wireframe: "Makieta",
  states: "Stany interfejsu",
  tokens: "Tokeny projektowe",
  components: "Komponenty",
  "design system": "System projektowy",
  handoff: "Przekazanie do wdrożenia",
  review: "Przegląd",
  architecture: "Architektura",
  "architecture review": "Przegląd architektury",
  build: "Wdrożenie",
  deploy: "Publikacja",
  deployment: "Publikacja",
  recovery: "Odzyskiwanie",
  rollback: "Wycofanie wdrożenia",
  backup: "Kopia zapasowa",
  restore: "Odtwarzanie",
  maintenance: "Utrzymanie",
  updates: "Aktualizacje",
  monitoring: "Monitoring",
  alerts: "Alerty",
  logs: "Logi",
  errors: "Błędy",
  security: "Bezpieczeństwo",
  permissions: "Uprawnienia",
  roles: "Role",
  domain: "Model domeny",
  data: "Dane",
  forms: "Formularze",
  dashboard: "Panel",
  editor: "Edycja",
  preview: "Podgląd",
  validation: "Walidacja",
  migration: "Migracja",
  relations: "Relacje",
  performance: "Wydajność",
  search: "Wyszukiwanie",
  scope: "Zakres",
  ownership: "Odpowiedzialność",
  routine: "Praca cykliczna",
  changes: "Zmiany",
  roadmap: "Plan rozwoju",
  backlog: "Lista rozwoju",
  release: "Wydanie",
  risk: "Ryzyko",
  intent: "Intencja",
  topics: "Tematy",
  links: "Linkowanie",
  answers: "Odpowiedzi",
  knowledge: "Baza wiedzy",
  clusters: "Klastry tematyczne",
  claims: "Twierdzenia",
  evidence: "Dowody",
  truth: "Weryfikacja faktów",
  services: "Usługi",
  "web app": "Aplikacja webowa",
  workflow: "Proces",
  observability: "Obserwowalność",
  frontend: "Warstwa frontowa",
  backend: "Zaplecze",
  environments: "Środowiska",
  artifact: "Artefakt",
  pipeline: "Proces wdrożeniowy",
  "static hosting": "Hosting statyczny",
  offline: "Tryb offline",
  install: "Instalacja",
  installation: "Instalacja",
  icons: "Ikony",
  metadata: "Metadane",
  fallback: "Tryb awaryjny",
  navigation: "Nawigacja",
  translation: "Tłumaczenie",
  locale: "Wersja językowa",
  implementation: "Wdrożenie",
  "content flow": "Przepływ treści",
  draft: "Wersja robocza",
  "search review": "Przegląd widoczności",
  "truth review": "Weryfikacja faktów",
  testing: "Testowanie",
  experiment: "Eksperyment",
  experiments: "Eksperymenty",
  hypothesis: "Hipoteza",
  metrics: "Metryki",
  measurement: "Pomiar",
  "technical seo": "SEO techniczne",
  "on-page": "SEO na stronie",
  "seo on-page": "SEO na stronie",
  "internal linking": "Linkowanie wewnętrzne",
  crawl: "Odkrywanie treści",
  indexing: "Indeksowanie",
  "content architecture": "Architektura treści",
  "crawl & index architecture": "Architektura odkrywania i indeksowania",
  "semantic structure": "Struktura semantyczna",
  "page signals": "Sygnały strony",
  "performance & quality": "Wydajność i jakość",
  headings: "Nagłówki",
  images: "Obrazy",
  "intent map": "Mapa intencji",
  "technical foundation": "Fundament techniczny",
  verification: "Weryfikacja",
  "answer-first": "Odpowiedź wprost",
  definitions: "Definicje",
  "semantic headings": "Semantyczne nagłówki",
  "entity clarity": "Jednoznaczność encji",
  "structured content": "Treść ustrukturyzowana",
  "source context": "Kontekst źródłowy",
  "question architecture": "Architektura pytań",
  questions: "Pytania",
  "answer-first sections": "Sekcje z odpowiedzią wprost",
  context: "Kontekst",
  copy: "Treść",
  "entity consistency": "Spójność encji",
  entities: "Encje",
  brand: "Marka",
  "public truth": "Publiczna prawda",
  consistency: "Spójność",
  "machine-readable support": "Wsparcie danych maszynowych",
  "source-friendly content": "Treść źródłowa",
  "structured data": "Dane strukturalne",
  "original evidence": "Oryginalne dowody",
  "entity map": "Mapa encji",
  entity: "Encja",
  organization: "Organizacja",
  "public-truth layer": "Warstwa publicznej prawdy",
  "citation-friendly content": "Treść przyjazna cytowaniu",
  sources: "Źródła",
  "original content": "Oryginalna treść",
  "technical support": "Wsparcie techniczne",
  identity: "Tożsamość",
  "machine layer": "Warstwa maszynowa",
  observation: "Obserwacja",
  "search architecture": "Architektura widoczności",
  "content systems": "Systemy treści",
  urls: "Adresy URL",
  "source of truth": "Źródło prawdy",
};

export function publicLabel(value: string) {
  return PUBLIC_LABELS[value.trim().toLowerCase()] ?? value;
}
