const PUBLIC_LABELS: Record<string, string> = {
  responsive: "Responsywność",
  mobile: "Mobile",
  "mobile-first": "Mobile-first",
  discovery: "Analiza potrzeb",
  content: "Treść",
  "user flow": "Ścieżka użytkownika",
  wireframe: "Makieta",
  states: "Stany interfejsu",
  tokens: "Tokeny projektowe",
  components: "Komponenty",
  "design system": "System projektowy",
  handoff: "Przekazanie do wdrożenia",
  review: "Przegląd",
  architecture: "Architektura",
  "architecture review": "Przegląd architektury",
  build: "Wdrożenie",
  deploy: "Publikacja",
  deployment: "Publikacja",
  recovery: "Odzyskiwanie",
  rollback: "Wycofanie wdrożenia",
  backup: "Kopia zapasowa",
  restore: "Odtwarzanie",
  maintenance: "Utrzymanie",
  updates: "Aktualizacje",
  monitoring: "Monitoring",
  alerts: "Alerty",
  logs: "Logi",
  errors: "Błędy",
  security: "Bezpieczeństwo",
  permissions: "Uprawnienia",
  roles: "Role",
  domain: "Model domeny",
  data: "Dane",
  forms: "Formularze",
  dashboard: "Panel",
  editor: "Edycja",
  preview: "Podgląd",
  validation: "Walidacja",
  migration: "Migracja",
  relations: "Relacje",
  performance: "Wydajność",
  search: "Wyszukiwanie",
  scope: "Zakres",
  ownership: "Odpowiedzialność",
  routine: "Praca cykliczna",
  changes: "Zmiany",
  roadmap: "Plan rozwoju",
  backlog: "Lista rozwoju",
  release: "Wydanie",
  risk: "Ryzyko",
  intent: "Intencja",
  topics: "Tematy",
  links: "Linkowanie",
  answers: "Odpowiedzi",
  knowledge: "Baza wiedzy",
  clusters: "Klastry tematyczne",
  claims: "Twierdzenia",
  evidence: "Dowody",
  truth: "Weryfikacja faktów",
  services: "Usługi",
  "web app": "Aplikacja webowa",
  workflow: "Proces",
  observability: "Obserwowalność",
  frontend: "Warstwa frontowa",
  backend: "Zaplecze",
  environments: "Środowiska",
  artifact: "Artefakt",
  pipeline: "Proces wdrożeniowy",
  "static hosting": "Hosting statyczny",
};

export function publicLabel(value: string) {
  return PUBLIC_LABELS[value.trim().toLowerCase()] ?? value;
}
