const REPLACEMENTS: readonly [RegExp, string][] = [
  [/\bcheckout \+ payments\b/gi, "koszyk, zamówienie i płatności"],
  [/\bbuild \+ integrations\b/gi, "wdrożenie i integracje"],
  [/\blaunch \+ rozwój\b/gi, "publikacja i rozwój"],
  [/\bdesign \+ build\b/gi, "projekt i wdrożenie"],
  [/\bsearch \+ data\b/gi, "widoczność i dane"],
  [/\bproduct data\b/gi, "dane produktowe"],
  [/\btechnical seo layer\b/gi, "warstwa SEO technicznego"],
  [/\banswer layer\b/gi, "warstwa odpowiedzi"],
  [/\bentity & geo layer\b/gi, "warstwa encji i GEO"],
  [/\bmachine-readable layer\b/gi, "warstwa danych maszynowych"],
  [/\bsearch architecture\b/gi, "architektura widoczności"],
  [/\bdesign system\b/gi, "system projektowy"],
  [/\bweb development\b/gi, "programowanie webowe"],
  [/\bresponsive design\b/gi, "projekt responsywny"],
  [/\bhero image\b/gi, "główny obraz"],
  [/\bfield data\b/gi, "dane rzeczywiste"],
  [/\bthird-party\b/gi, "zewnętrzne usługi"],
  [/\bbefore-state\b/gi, "stan przed zmianą"],
  [/\bdevelopment\b/gi, "programowanie"],
  [/\bdeployment\b/gi, "wdrożenie"],
  [/\bdesign\b/gi, "projektowanie"],
  [/\bresponsive-first\b/gi, "od wersji responsywnej"],
  [/\bmobile-first\b/gi, "od wersji mobilnej"],
  [/\bresponsive\b/gi, "responsywność"],
  [/\bmobile\b/gi, "urządzenia mobilne"],
  [/\bwireframe\b/gi, "makieta"],
  [/\blanding pages?\b/gi, "strony kampanijne"],
  [/\bcampaign ux\b/gi, "UX kampanii"],
  [/\bmessage architecture\b/gi, "architektura komunikatu"],
  [/\bfast build\b/gi, "lekkie wdrożenie"],
  [/\btracking\b/gi, "pomiar"],
  [/\bprofiling\b/gi, "profilowanie"],
  [/\bcommerce architecture\b/gi, "architektura sprzedaży"],
  [/\bproduct experience\b/gi, "doświadczenie produktu"],
  [/\bcheckout\b/gi, "proces zakupu"],
  [/\bpayments\b/gi, "płatności"],
  [/\bcatalog\b/gi, "katalog"],
  [/\bshipping\b/gi, "dostawa"],
  [/\bintegrations\b/gi, "integracje"],
  [/\bautomation\b/gi, "automatyzacja"],
  [/\bcustom\b/gi, "dedykowane"],
  [/\blaunch\b/gi, "publikacja"],
  [/\bbuild\b/gi, "wdrożenie"],
  [/\bvalidation\b/gi, "walidacja"],
  [/\bperformance\b/gi, "wydajność"],
  [/\bsecurity\b/gi, "bezpieczeństwo"],
  [/\baccessibility\b/gi, "dostępność"],
  [/\banalytics\b/gi, "analityka"],
  [/\bevents\b/gi, "zdarzenia"],
  [/\bfunnel\b/gi, "lejek"],
  [/\bforms\b/gi, "formularze"],
  [/\boffer\b/gi, "oferta"],
  [/\bcopy structure\b/gi, "struktura treści"],
  [/\blocal intent\b/gi, "intencja lokalna"],
  [/\blocal pages\b/gi, "strony lokalne"],
  [/\breviews\b/gi, "opinie"],
  [/\bareas\b/gi, "obszary"],
  [/\bprofile & schema support\b/gi, "wsparcie profilu i danych strukturalnych"],
  [/\bsource of truth\b/gi, "źródło prawdy"],
  [/\bpublic truth\b/gi, "publiczna prawda"],
  [/\bstructured data\b/gi, "dane strukturalne"],
  [/\btechnical seo\b/gi, "SEO techniczne"],
  [/\bon-page\b/gi, "na stronie"],
  [/\binternal linking\b/gi, "linkowanie wewnętrzne"],
  [/\bcontent architecture\b/gi, "architektura treści"],
  [/\bcontent\b/gi, "treść"],
  [/\bentity consistency\b/gi, "spójność encji"],
  [/\bentity map\b/gi, "mapa encji"],
  [/\bentity clarity\b/gi, "jednoznaczność encji"],
  [/\bsource-friendly content\b/gi, "treść przyjazna źródłom"],
  [/\bcitation-friendly content\b/gi, "treść przyjazna cytowaniu"],
  [/\boriginal content\b/gi, "oryginalna treść"],
  [/\boriginal evidence\b/gi, "oryginalne dowody"],
  [/\btechnical support\b/gi, "wsparcie techniczne"],
  [/\bmachine layer\b/gi, "warstwa maszynowa"],
  [/\bquestion architecture\b/gi, "architektura pytań"],
  [/\banswer-first sections\b/gi, "sekcje z odpowiedzią wprost"],
  [/\banswer-first\b/gi, "odpowiedź wprost"],
  [/\banswer engines?\b/gi, "systemy odpowiedzi"],
  [/\bsemantic headings\b/gi, "semantyczne nagłówki"],
  [/\bstructured content\b/gi, "treść ustrukturyzowana"],
  [/\bsource context\b/gi, "kontekst źródłowy"],
  [/\bcrawlability\b/gi, "dostępność dla robotów"],
  [/\bcrawler\b/gi, "robot indeksujący"],
  [/\bredirects?\b/gi, "przekierowania"],
  [/\bbackend\b/gi, "zaplecze serwerowe"],
  [/\bstack\b/gi, "stos technologiczny"],
  [/\bprovider\b/gi, "dostawca"],
  [/\bfallback\b/gi, "tryb awaryjny"],
  [/\bviewport\b/gi, "obszar widoku"],
  [/\bfont\b/gi, "krój pisma"],
  [/\bmotion\b/gi, "ruch"],
];

export function publicText(value: string) {
  let result = value;
  for (const [pattern, replacement] of REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }
  return result;
}
